### ISSUE TITLE
Resources aren't being consumed when you use them through the token action hud

### ISSUE THREAD

**Issue by Avitale34** [espositos/fvtt-tokenactionhud#1]
Resources aren't being consumed when you use them through the token action hud, for example Longbow using arrows, or wand of fireballs

**Comment by espositos** [comment]
I will keep an eye on this, but I think it is an issue with BetterRolls for the moment. There is also an issue when casting spells from an unlinked token that the main actor/character's spell slots are expended as well/instead.
