### ISSUE TITLE
[Pathfinder 2e] Always abbreviated skill and ability names

### ISSUE THREAD

**Issue by Cosmic-Lattee** [espositos/fvtt-tokenactionhud#101]
Thank you for fixing the error from yesterday! I was doing some game prep today and I noticed that now even with abbreviate skill and ability names clicked off it always does skills abbreviated (see picture below). I tested this in a new game using 0.7.6 (Foundry), 1.10.15.2210 (Pathfinder) and 0.8.15 (Token Action HUD) with no other modules active.

Abilities still works properly though I forgot to take a picture of that.

![image](https://user-images.githubusercontent.com/24766235/98493450-19047900-2200-11eb-9f45-2cccc1114c4a.png)

**Comment by Cosmic-Lattee** [comment]
To add onto this now when clicking on lores from the action hud they don't seem to do anything.

**Comment by espositos** [comment]
Ah, Lore skills are apparently rolled differently now as well. Sorry, I will fix that.
