### ISSUE TITLE
[Pathfinder 2e] Monster Skills Don't Work

### ISSUE THREAD

**Issue by Cosmic-Lattee** [espositos/fvtt-tokenactionhud#102]
Hello there!

Player skills seem to work perfectly but now when I try to roll monster skills they don't seem to work. Clicking on them does nothing. 

Tested with Foundry 0.7.6, PF2e 1.10.15.2210, and the current version of Tokenactionhud.

**Comment by espositos** [comment]
Thanks for the report. I'll look into it.

**Comment by espositos** [comment]
Should be fixed
