### ISSUE TITLE
PF1: Spontaneous caster's spells aren't listed

### ISSUE THREAD

**Issue by Ironxxx** [espositos/fvtt-tokenactionhud#103]
The mod seems to list spells for PF1 due to being selected as memorised. However, spontaneous casters such as sorcerers, hunters and oracles do not select spells to memorise, they just know them but cannot select from a range of spells. This causes the mod not to list anything. There needs to be recognition for the Spontaneous caster flag which would then list all spells for that caster class no matter if "memorised" or not.
EDIT: It's worth noting that the Show Empty Items option does not show spontaneous caster spells.

**Comment by espositos** [comment]
Thank you for the PR, it's in 0.9.3.
