### ISSUE TITLE
Request for things with no "action" to not appear

### ISSUE THREAD

**Issue by millieloop** [espositos/fvtt-tokenactionhud#105]
Hey, love the mod, but a small request....
When a new player sets up a PC, they end up having 'buttons' for things like "rope", "rations", "common clothes". These things don't any sort of "Activation Cost" and are often blank.

It makes sense if they have a 'cost' of....
Action
Bonus Action
Reaction
Special
Lair

but could you perhaps set it so when NOTHING and well as "None" are selected 
![Capture](https://user-images.githubusercontent.com/72041263/98879050-81f82500-247c-11eb-95bd-6f3da7b22813.PNG)
by default doesn't show in the HUD bar? - Keep up the amazing work

**Comment by espositos** [comment]
Sounds sensible, I'll implement it.

**Comment by espositos** [comment]
If you have any issues with it or it's not working as you expected, let me know.
