### ISSUE TITLE
Error with tokens that are not attached to actors

### ISSUE THREAD

**Issue by itamarcu** [espositos/fvtt-tokenactionhud#106]
Whenever you hover over any token, if the scene contains another token that does not have an actor associated with it (represented actor = none, link actor data false), an error message is thrown into the console.

The culprit is this line (around line 420):

```js
            let token = canvas.tokens.placeables.find(t => t.actor._id === character._id)
```

It should probably be fixed, to become:

```js
            let token = canvas.tokens.placeables.find(t => t.actor && t.actor._id === character._id)
```

Similarly:
```js
        return game.user.isGM || actor.hasPerm(user, "OWNER");
```

**Comment by espositos** [comment]
I've added the checks in 0.9.4. If you still get the errors let me know and I will have to come up with a more resilient solution.
