### ISSUE TITLE
PF2 Shift-Click functionality

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#11]
Would love to see the shift-click functionality to allow additional modifiers be added to the damage buttons for attacks as well. Currently only available for the strike buttons. Also, really love this mod! Thanks for making it. :)

**Comment by espositos** [comment]
I'll look into it

**Comment by espositos** [comment]
For the moment, the damage buttons in the core game don't support shift click functionality (although they allow it anyway). The HUD will do the same.
