### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by west1778** [espositos/fvtt-tokenactionhud#111]
Not getting any bar at all with latest update and getting console error when trying to use newest Token action hud of 

![image](https://user-images.githubusercontent.com/73608023/99889890-7bf60700-2c27-11eb-8ff2-76ee9079956e.png)

**Comment by MS-PBS** [comment]
While this is getting fixed, you can make it work by having an empty encounter in the current scene. It doesn't even have to be active, it just has to be there.

**Comment by west1778** [comment]
Thank you for the quick reply.

**Comment by espositos** [comment]
Should be fixed in the latest patch, sorry about that!

**Comment by west1778** [comment]
Thank you for your help!   
  
  
  
  
  
    
  

  
  
>
