### ISSUE TITLE
[PF2] Have the Utility Option to rest for the night restore spell slots.

### ISSUE THREAD

**Issue by Unikatze** [espositos/fvtt-tokenactionhud#116]
Thanks for literally one of the most useful modules out there. 

Right now the "Rest for the Night" option only restores HP, SP, and Resolve points. 

Any chance for it to also add these functions?

Remove Fatigued Condition
Restore Spell slots
Reduce Drained and Doomed conditions by 1

**Comment by espositos** [comment]
Hey Unikatze, the 'Rest for the Night' function just runs the 'Rest for the Night' macro in the PF2 default macros compendium. To change it, either update that macro in the compendium so it does the things you want, or create a separate macro that does those things and add it to the HUD via a custom subcategory:
https://github.com/espositos/fvtt-tokenactionhud/blob/master/custom_categories.md

**Comment by espositos** [comment]
Feel free to contact me on Discord (^ and stick#0520) if you need help setting it up.
