### ISSUE TITLE
Feature request: Make it obvious if a toggle is active while also hovering over it

### ISSUE THREAD

**Issue by jacobjorvang** [espositos/fvtt-tokenactionhud#117]
Right now you can't tell if it's toggled on or off while hovering over it.

The toggle addition is amazing for PF2e rule elements, by the way. Thank you!

**Comment by espositos** [comment]
any ideas on how this should look?

**Comment by jacobjorvang** [comment]
Maybe a semi-transparent reddish background that stays when enabled, whether hovering or not. Same color as outline but more transparent I think.

**Comment by espositos** [comment]
It's in the latest patch (9.26), but let me know if you have feedback on the colour I've chosen.

**Comment by jacobjorvang** [comment]
Look perfect. Thank you!
