### ISSUE TITLE
Weird Incompatibility with Combat Tracker Effect Icon Tooltips

### ISSUE THREAD

**Issue by Flintwyrm** [espositos/fvtt-tokenactionhud#118]
![Screenshot_556](https://user-images.githubusercontent.com/60701064/100657324-16d39d00-331c-11eb-8e3f-939984e4ef9b.png)
there are supposed to be Icons that show in the combat tracker like this:
![Screenshot_550](https://user-images.githubusercontent.com/60701064/100657685-539f9400-331c-11eb-9082-e9f9237b162b.png)
But when Action HUD is active this happens. Only showing the first Icon.
![Screenshot_555](https://user-images.githubusercontent.com/60701064/100657408-3965b600-331c-11eb-97b8-4fcd508f0a9f.png)

**Comment by espositos** [comment]
Oops. My css skill is pretty dodgy, but I've implemented what I think is a fix in the latest patch (0.9.27). Let me know if it doesn't work.
