### ISSUE TITLE
PF2 - HUD showing ALL known spells

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#12]
HUD showing all spells known vs spells memorized. Not sure if this was intentional or not, but I thought I would mention it. 

![HUD Spells](https://user-images.githubusercontent.com/65833146/85960608-9a4a2600-b959-11ea-97a5-6fdb858a2edf.png)

**Comment by espositos** [comment]
Not intentional, just I don't know enough about the PF2E system yet. Thanks for reporting it, I'll work on it.
