### ISSUE TITLE
Request: Allow crit damage from BetterRolls5e's formula

### ISSUE THREAD

**Issue by miromonti** [espositos/fvtt-tokenactionhud#120]
Thanks for TokenActionHUD. It’s a great convenience. I’ve added [RedReign’s BetterRolls5e](https://github.com/RedReign/FoundryVTT-BetterRolls5e) and it’d be great to have its Critical Damage calculation instead of Foundry’s default. Maybe the feature already exists and I haven’t chosen the correct option(s)? If that’s so, then let me know what to turn on or which selection to choose to make it work. Otherwise, please consider adding this ability.

**Comment by espositos** [comment]
I am not sure how you have it set up, but if you look under the Token Action HUD settings you can select Better Rolls as the 'roll handler' for attacks made via the HUD. They will then be made using your normal 'quick roll' defaults, and if you hold alt while clicking an 'alt roll' will be made. Does that solve your problem?

**Comment by miromonti** [comment]
Thanks so much for your response. Your solution worked a treat. I don't know how or why I skipped the HUD roll handler. Be well and be safe!
