### ISSUE TITLE
Add support for PF2e Strikes for NPCs

### ISSUE THREAD

**Issue by Puddinglord** [espositos/fvtt-tokenactionhud#121]
Currently, you handle player strikes correctly. PF2e core just released an update to now give that same `Strike` category to NPCs as well.

Could you update Token Action HUD to use those new NPC `Strikes`?

If you need more explanation let me know.

**Comment by Puddinglord** [comment]
I want to add that right now this new `Strike` category for NPCs is labeled as **experimental**. With that in mind, I think the best thing to do would be to add all the attacks/weapons to the HUD. That way I can roll the new strikes as they are labeled `Strike: ` before the attack name. If there's something wrong though and the attack or damage doesn't work I should be able to use the old weapons/strikes as a backup.

This is more of a *nice to have* feature and I completely understand if you only do the new strikes. It's not that big of a deal for me to open the NPCs character sheet if the attacks fail because of the experimental nature of the new strikes.

Also, thanks! I love Token Action HUD and so do all my players. They thought it was a standard feature of Foundry and when I told them it's not they were like, "Why not?!".

**Comment by espositos** [comment]
Should be added now. There is an option in the settings to disable showing the old NPC strikes
