### ISSUE TITLE
[Pathfinder 2] Show Passive Actions bug

### ISSUE THREAD

**Issue by Cosmic-Lattee** [espositos/fvtt-tokenactionhud#122]
Hello again!

Thank you again for all your hard work on this project! :)

So something I noticed is that if passive actions is enabled they still don't show up in the actions tab:

![image](https://user-images.githubusercontent.com/24766235/101437652-4ebb8100-38d6-11eb-8ae9-3273cac6da43.png)

Tested using:
Foundry: 0.7.8
PF2 System: 1.10.20.2419
Token Action HUD: 0.10.2

**Comment by espositos** [comment]
Thanks for the report, I'll look into it.

**Comment by espositos** [comment]
I think this is resolved but let me know if there are still issues
