### ISSUE TITLE
Roll same skill/ save/ perception on multiple tokens [Pf2e]

### ISSUE THREAD

**Issue by EldritchDream** [espositos/fvtt-tokenactionhud#123]
Would making multiple selected tokens roll the same skill or save be easy enough to add?

**Comment by espositos** [comment]
It is difficult for PF2E, at least last time I checked, because NPCs and PCs do not handle saves the same way. Skill rolls might be possible. I will re-examine it.

**Comment by espositos** [comment]
I have added multiple rolls for abilities and saves, but skills are difficult because NPCs are not guaranteed to have a particular skills to roll. If you have any ideas, let me know.
