### ISSUE TITLE
Add Blind GM rolls using modifier keys

### ISSUE THREAD

**Issue by JamzTheMan** [espositos/fvtt-tokenactionhud#125]
PF2E has a LOT of "secret" rolls that the GM requests. Could you make ALT+Click or right-click or some such execute a Blind roll?

This really is only needed on Skill rolls but doesn't have to be limited to them.  This would save so much time and not interrupt the flow of the game during interactions.

**Comment by espositos** [comment]
Implemented in 0.10.6 via ctrl+click. It will effect everything clickable. All it does is set the roll mode to blind roll, do what it needs to, and then set the roll mode back to whatever it was previously. Let me know if there are any issues.
