### ISSUE TITLE
[sfrpg] Add support for new Starship sheet

### ISSUE THREAD

**Issue by supernovajm** [espositos/fvtt-tokenactionhud#126]
The latest update to the sfrpg system added starship actions. It would be great to have these in the action hud when the ship token is selected.

![image](https://user-images.githubusercontent.com/24704061/101999044-f229de80-3ca6-11eb-811d-c6719e9e9d75.png)

Please also add support for firing the guns from the ship token.

![image](https://user-images.githubusercontent.com/24704061/101999024-b1ca6080-3ca6-11eb-87c4-f99b4eb5c7a0.png)

Another thing that would be really handy is some way to manage shields from the action hud, because there's no easy way to track 4 health bars on a single token in foundry. Maybe some +/- buttons for each quadrant, in increments of 1/5/10.

**Comment by espositos** [comment]
Hey, I'll try to add this soon, if I find some time.

**Comment by espositos** [comment]
Hey, support is added in the latest patch. If anything needs changing, let me know. One thing to note, the Starship Crew Actions are hard to implement at the moment and I am waiting for an improvement in the SFRPG API that should arrive with their next patch. Then Crew Actions will show up.
