### ISSUE TITLE
Inventory items activated through HUD don't use Midi QOL settings in 5e

### ISSUE THREAD

**Issue by amcvfx** [espositos/fvtt-tokenactionhud#127]
This may have happened after the lastest update to MidiQOL (0.3.36) but Weapon items used through the Token Action HUD don't have the same behaviour as when used through the character sheet. 
Instead of activating a Midi QOL speed roll it creates chat card with Attack and Damage buttons. It skips the Midi QOL flags because of this.

![image](https://user-images.githubusercontent.com/35099081/102066441-1ea23f80-3dfa-11eb-9ffc-ba526bb92ff3.png)

Foundry 0.7.8
D&D 5th 1.2.0
Token Action HUD 0.10.8

**Comment by espositos** [comment]
I'll look into it, thanks for reporting it :)

**Comment by dirusulixes** [comment]
Yeah, I can confirm the issue with the same configuration.

**Comment by espositos** [comment]
This should be resolved by updating MidiQoL to the latest version
