### ISSUE TITLE
DND5E: Was using the Token Action HUD and now it doesn't appear anymore.

### ISSUE THREAD

**Issue by jerichojx** [espositos/fvtt-tokenactionhud#13]
Tried removing all mods and it still doesn't work. I deleted the mod and reinstalled and it still doesn't work.

**Comment by espositos** [comment]
I'll look into it.

**Comment by jerichojx** [comment]
Hi

I added you as a friend on on Discord but I am not sure if I did it correctly. I am saiyanjesus#7647.

I am running Dungeon and Dragons 5th Edition, version 0.93.
Foundry version is 0.6.4

![Token Action Bar](https://user-images.githubusercontent.com/67579273/86065231-4ba3a580-ba99-11ea-8a8a-d942520813a0.png)

As you can see, I can only get Token Bar working but not Token Action Bar.
