### ISSUE TITLE
My Hud disappears every time I restart Foundry

### ISSUE THREAD

**Issue by EikePeace** [espositos/fvtt-tokenactionhud#132]
Whenever I update my modules, reload the game or reopen foundry, I have to reinstall the module again.

It works fine in the browser for my players and even me, just the app itself has problems.

Any idea, why that could be?

The only error I get in the console after enabling token action hud is "Uncaught Syntax Error: Invalid or unexpected token actionListExteder.js:1"

The file consists of 190 red dots.

**Comment by espositos** [comment]
Strange, I've sent you a message on Discord.
