### ISSUE TITLE
[PF2e Request] Possible to not show items that are not worn?

### ISSUE THREAD

**Issue by zLaddeus** [espositos/fvtt-tokenactionhud#135]
Currently when using the Hud with Pathfinder 2e every item that is on the character sheet is displayed, under Strikes and Inventory.

Would it be possible to not show Items or Weapons when they are currently not being worn, or put inside a container?

Strikes. Under strike all weapons on a characters sheet are being shown, even if they are not worn or put away in a container.
Inventory. Shows all items, even if they are not worn or put away in a container.

**Comment by espositos** [comment]
Should be done int he latest patch, but let me know if there's still something that doesn't fit your request
