### ISSUE TITLE
PF1e shows incorrect charges remaining for items with linked charges

### ISSUE THREAD

**Issue by mkahvi** [espositos/fvtt-tokenactionhud#136]
If the charges are linked, the remaining charges are shown wrong.

Here you can see the wrong behaviour:  
![Screenshot 2020-12-29 073906](https://user-images.githubusercontent.com/8120158/103261148-0fe68b80-49a9-11eb-8ed4-6893ddd9ec20.png)  
Kinetic Healer has its charges linked to Burn feature and should as such match.

The character sheet shows it correctly, so this is unique problem with TAHUD:  
![Screenshot 2020-12-29 073940](https://user-images.githubusercontent.com/8120158/103261151-107f2200-49a9-11eb-8512-2ee67cd5457b.png)

**Comment by espositos** [comment]
Hey @mkahvi, I'm sorry, I think this has been resolved in one of the patches from the Pathfinder team, but the trouble is because I don't know the system I find it hard to replicate anyway. Can you please test it with the latest version of both HUD and PF1 and let me know if the issue still exists? If it does, I'll take another look at it.

**Comment by mkahvi** [comment]
Still present.

Kinetic healer has its charges linked to Burn, yet they show the numbers wrong.  
![Screenshot 2021-01-11 150444](https://user-images.githubusercontent.com/8120158/104186053-8316e580-541e-11eb-8aae-47ff12efc909.png)

I thought it might've been caching something, since the character did have the burn pool at max 7 until I changed a buff. But I applied sheet update couple of extra times to make sure that wasn't the case but it refuses to catch up.

PF1e 0.76.11
TAHUD 0.10.22
FVTT 0.7.9

Maybe it's fixed for the upcoming PF1e release? I don't know.

**Comment by espositos** [comment]
I'll take another look into it in the next couple of days. Thanks for the feedback!

**Comment by mkahvi** [comment]
Here's a minimal actor with the bug happening:  
[fvtt-Actor-charge_link_bug.zip](https://github.com/espositos/fvtt-tokenactionhud/files/5800273/fvtt-Actor-charge_link_bug.zip)

It shows no charges for the secondary feature despite them being linked and showing correctly in the sheet.  
![Screenshot 2021-01-12 090403](https://user-images.githubusercontent.com/8120158/104280817-29152f00-54b5-11eb-8c91-7a7997b66932.png)

Tested also on the master branch of PF1e, where the problem is as reproducible.

**Comment by espositos** [comment]
Could you try the latest version? I may have found a fix.

**Comment by mkahvi** [comment]
Yep, looks to be working correctly now. Thanks!
