### ISSUE TITLE
PF2E Containers do not show up even when wearing them

### ISSUE THREAD

**Issue by JerkyGunner** [espositos/fvtt-tokenactionhud#138]
I'd like to enable some containers for a couple of players as they store reference items in them but setting the containers to "worn" doesn't make them show up on the HUD.

**Comment by espositos** [comment]
Can you tell me what this should look like? Is the container just the item or should each container be it's own subcategory containing its contents?

**Comment by JerkyGunner** [comment]
I would say each container that is 'worn' should be it's own subcategory.

![image](https://user-images.githubusercontent.com/11801379/103407501-33533700-4b5f-11eb-977d-f945baf608c3.png)

In this example, I use a container to represent the alchemist's formula book (which isn't yet properly implemented in the system) and which I'd like the options to be visible for. I can imagine it being useful for other containers, however, particularly if the player is careful about putting items into containers rather than just having them be part of their inventory.

**Comment by espositos** [comment]
In the latest patch, but let me know if there are any issues.

**Comment by JerkyGunner** [comment]
It doesn't seem to be working for me. Do I need to change any settings or do something in particular to enable it?

The character is "wearing" the container but it's not showing up on the HUD. (Same with other characters and other containers)

**Comment by espositos** [comment]
No, you shouldn't need to. I'll look into it again

**Comment by espositos** [comment]
As far as I can tell it should be working. It identifies the container based on two things: is it equipped and does it have a bulk capacity value. If both these things are true it should work properly.

**Comment by espositos** [comment]
Seems to be fixed in 10.18
