### ISSUE TITLE
PF2 - DM can roll damages, but players can't. 

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#14]
On DM side, he can roll player's strikes and strike damage rolls. Player's however get the roll dialog rather than the roll and the dialog is broken and the roll cannot be made. 

![image](https://user-images.githubusercontent.com/4083812/86062659-e4262f80-ba71-11ea-88f6-85a14431b4a1.png)

**Comment by apoapostolov** [comment]
As discussed on Discord: the issue is that players behavior on damage is same as shift-click, which doesn't work. Instead it should be normal click.

**Comment by espositos** [comment]
More an issue with PF2E itself. Apo has submitted an issue with the PF2E devs:
https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/570
