### ISSUE TITLE
[FEATURE] : integration with MARS-5e and switching advantage/disadvantages from Token HUD

### ISSUE THREAD

**Issue by davidR1974** [espositos/fvtt-tokenactionhud#141]
My players (and myself :)) always forgot what is the keyboard shortcuts for advantaged / disadvantaged rolls from the token HUD.

MARS-5e interface offers a great way of selecting advantage/disadvantage by right-clicking on a rollable item and display a tooltip showing "normal" / "advantage" / "disadvantage"

This could be useful to integrate with this module either :
* by allowing rolls to be sent to MARS-5e (enabling Ctrl or Alt clicks to make an disadvantaged / advantaged roll)
* by replicating the function of right clicking on HUD item to loop between ADV / DIS / NORmal with a tooltip reminder or an icon reminder or a color code reminder.

**Comment by espositos** [comment]
So as far as I can tell - please correct me if I'm wrong - the Token Action HUD already works with MARS if you have the 'core' roller options selected.

![image](https://user-images.githubusercontent.com/14127543/104106959-7036d080-52b9-11eb-9e9f-76461ecc408d.png)

As a reminder, the controls for advantage and disadvantage with the core rolls are control for disadvantage and alt for advantage. If you were using MidiQoL or BetterRolls they may be different and should align with whatever those modules use for advantage and disadvantage. I might consider adding some other kind of indication about which roll is chosen in the future but this would be a long (long) way off.

**Comment by davidR1974** [comment]
Sorry,, should have added some precisions..

Dis / Adv shotcuts are not working for attack rolls unless you validate Adv/Dis from the inventoy sheet before (or from the toolbar if the item is moved to the toolbar)..

**Comment by espositos** [comment]
I'll contact Moerill and see how MARS supports advantage and disadvantage.

**Comment by espositos** [comment]
MARS now supports advantage and disadvantage on rolling via control for disadvantage and alt or shift for advantage. It should work from the HUD as well.

**Comment by espositos** [comment]
I will bear in mind the idea of a tooltip for advantage and disadvantage but it won't be implemented soon, so for the moment I will close this issue. Feel free to reopen it if there are still issues.

**Comment by davidR1974** [comment]
tested this morning and works fine.
