### ISSUE TITLE
Non-working HUD displayed after token is removed from scene

### ISSUE THREAD

**Issue by Blesmol** [espositos/fvtt-tokenactionhud#142]
Reproduce:
1. Have token on scene
2. Select token so that HUD is displayed
3. Deselect token
4. Have GM remove token
5. HUD is still displayed, but does not result in any rolls

If the player still has the token selected when it is deleted from the scene, then the HUD menu also vanishes together with the token

**Comment by espositos** [comment]
Thanks for reporting, I'll investigate

**Comment by espositos** [comment]
Should be fixed in the latest version

**Comment by Blesmol** [comment]
Great, thanks!
