### ISSUE TITLE
PF2e open/post effect items

### ISSUE THREAD

**Issue by Drental** [espositos/fvtt-tokenactionhud#149]
With the continuing adoption of Effect items (and Rule elements) into the system, it'd be nice to be able to open/post the Errect items on a character in a similar way that features and feats can be opened/edited. The opened windows from Token Action Hud are actually more functional than those opened from the sheet - you can drag/drop effects right from them onto the token and don't have to post them to chat, so that's good.

Sincerely, a fan.

**Comment by espositos** [comment]
Should be in the latest patch
