### ISSUE TITLE
The configuration checkbox "Show all non-preparable spells" seem not work properly

### ISSUE THREAD

**Issue by p4535992** [espositos/fvtt-tokenactionhud#15]
**Detail of the world:**

Foundry Virtual Tabletop, version 0.6.4
System Core: Dungeons and Dragons 5th Edition, version 0.92
Modules Installed: Token Action HUD, version 0.2.10

**Description of the issue:**
On the configuration of the module i checked the checkbox "Show all non-preparable spells", but it's seem not show the spell if i'm not set "Prepared" on the details of the spell.

![bug1](https://i.imgur.com/DMpQTH7.jpg)

When i set "Prepared" the tab spell show and work like expected.

![bug2](https://i.imgur.com/CPunMDZ.jpg)

**Comment by espositos** [comment]
Thanks for reporting it!

**Comment by espositos** [comment]
Should be fixed, let me know if you find anything else :)
