### ISSUE TITLE
Starfinder: Ships with NPC crews have no actions shown

### ISSUE THREAD

**Issue by agentnos** [espositos/fvtt-tokenactionhud#158]
When you create a starship with an NPC crew the only actions shown are the free crew actions regardless of the crew makeup.
If I add a pilot and a science officer for example, none of their specific actions show up, unlike when there are actual tokens in the crew slots.

(aside from that, it's implememnted really nicely for starfinder and I just wanna thank you for making life easier for my players and I!!)

**Comment by espositos** [comment]
Hey, I'll try to look into this today.

**Comment by espositos** [comment]
Should be fixed in latest patch
