### ISSUE TITLE
Boxes move up and down slightly on hover in Foundry native app

### ISSUE THREAD

**Issue by ZBell** [espositos/fvtt-tokenactionhud#16]
Hello, I'd like to say first that I think this is an excellent module, but I noticed a little issue when hovering over a button.  The buttons would all jump a couple of pixels as the border was added to the hovered button.  I fixed it by just adding a transparent border around the buttons instead of leaving it as none when not hovering.  I included the tweaked style below, I don't know much about web design so I don't know if this has other negative effects elsewhere.  Anyway, thanks for all your great work on the module!

.tah-title-button {
    width: auto;
    height: auto;
    color: #fff;
    background: rgba(52, 52, 52, 0.95);
    padding: 3px;
    margin: 3px;
    **border: 1px solid transparent;**
    cursor: pointer;
}

**Comment by espositos** [comment]
That's great, thank you! I also don't know anything about web design and the CSS is definitely a weak area. I'll add your change to the next patch.
