### ISSUE TITLE
Cyberpunk RED/2020 support

### ISSUE THREAD

**Issue by Un-4g1v3n** [espositos/fvtt-tokenactionhud#160]
Cyberpunk RED support would be appreciated. I might have a friend who could work on the coding, but I'm not sure of his schedule. Would appreciate this added system.

**Comment by espositos** [comment]
Hey, I'm sorry, as with all the other new system requests, I have no time to support additional systems but I welcome pull requests. Sorry to disappoint.

**Comment by sedge** [comment]
@espositos Hey! I'm happy to take this on. Reopen the issue and I'll file a PR against it.

Thanks for your great work!
