### ISSUE TITLE
Enlarged Mode

### ISSUE THREAD

**Issue by Alexis-Grimm** [espositos/fvtt-tokenactionhud#163]
Hello, both me and one of my players have poor eyesight and find the token hud a little too small, I was wondering if it would be possible to add in a setting that scales it up somewhat. Otherwise love the module thanks a ton!

**Comment by espositos** [comment]
Hey! It's a good idea, I will look into how to implement this.

**Comment by espositos** [comment]
Hi, I've added a scale slider in the settings as of patch 0.10.32. I'd really appreciate if you could try it out and let me know if it meets your needs.
