### ISSUE TITLE
One player is missing inventory

### ISSUE THREAD

**Issue by TroubledPitcher** [espositos/fvtt-tokenactionhud#164]
I have a single player who's inventory is not appearing in the token hud. Other characters don't seem to have this issue.

**Comment by espositos** [comment]
Hey TroubledPitcher, I think I've messaged you on Discord, but I have the following questions:
Do you mean the HUD doesn't appear at all, or they see the HUD but don't see an inventory category?
Can the GM see the inventory if they click on the user's token?
Do any errors appear in the console when selecting the token?
Is it possible the HUD has been dragged off screen? They may need to run this command:
`game.tokenActionHUD.resetHud();`

If the problem only affects the inventory but the other categories are visible, generally things only appear in the inventory when they are equipped (depending which system you're using). Are there items equipped in the inventory that you would expect to see in the HUD?

Let me know here or on Discord (^ and stick#0520)
