### ISSUE TITLE
Drop up menu

### ISSUE THREAD

**Issue by fredrlw** [espositos/fvtt-tokenactionhud#166]
Hi, first off I wanna say that me and my players really love the token action hud. 

But my players have asked me if it is possible to make the HUD drop up instead?

So here I am, asking if it is possible to add a setting to make the HUD drop up instead of down

**Comment by espositos** [comment]
Just to set your expectations, I am currently very busy and focusing more on maintenance, but it is a good idea and I will look into it.

**Comment by espositos** [comment]
I think this might be easy if I implement a really half-assed drop-up effect. I'll add it in and you can give me feedback. If it neesd more work that will definitely need more time.

**Comment by espositos** [comment]
It's added in the latest patch. Let me know if it meets your requirements and/or could be improved (there are limitations to this, but let me know what you think anyway).

**Comment by fredrlw** [comment]
Didn't expect you to do anything with it so soon, but yeah, it is exactly what we wanted. And from what I can see right now it works just as before. So thanks alot
