### ISSUE TITLE
Token Action Hud 0.3.0 Interaction with RollOptions

### ISSUE THREAD

**Issue by Valdacil** [espositos/fvtt-tokenactionhud#17]
Per nikolaj-a I developed a script for setting rollOptions for Sneak Attack dice and one for the player to toggle the 'flat-footed' condition to roll Sneak Attack.  nikolaj-a helped me develop these scripts which are essentially his code for making rollOptions with a little bit of feedback for the player.  So first they use the following macro to set their Sneak Attack dice:
https://github.com/Valdacil/FoundryPF2EMacros/blob/master/Sneak.Attack.Set.Dice.Player.js
Then use the following macro to toggle 'flat-footed' rollOption so Foundry rolls Sneak Attack with the damage:
https://github.com/Valdacil/FoundryPF2EMacros/blob/master/Sneak.Attack.Toggle.Player.js

This was all working a day or two ago.  Tonight while trying to run the game my player could not get Foundry to roll Sneak Attack in the way described by nikolaj-a.  Using console.log(actor) on his token showed that the damageDice for Sneak Attack was present conditional on 'flat-footed' and rollOption 'flat-footed' = TRUE, so it should have been rolling Sneak Attack, but wasn't.  After the session I disabled Token Action Hud and Sneak Attack immediately started working as nikolaj-a described.  So it appears to be an interaction when TAH is enabled that blocked the rollOptions from working properly.

**Comment by espositos** [comment]
I think I've identified the problem with nikolaj's help. Should be in the next patch

**Comment by Valdacil** [comment]
Awesome.  Glad it wasn't anything too major and you were able to fix it quickly.  My players love the HUD and we're looking forward to the enhancements you were talking about in Discord with options to remove things like Attributes and other things they will never use.  Nice clean interface with only usable items :)
