### ISSUE TITLE
Request: Add a Recovery Check roll

### ISSUE THREAD

**Issue by Mr-Monocyte** [espositos/fvtt-tokenactionhud#170]
Quick access to automated recovery checks would be helpful.

**Comment by espositos** [comment]
Hey, sorry, which system are you talking about? And sorry it's taken so long to reply.

And a screenshot of from the sheet that you want to replicate would be great.

**Comment by espositos** [comment]
Hey, sorry, I am going to close this in the absence of further feedback. If you have more information in the future please feel free to write a new ticket.
