### ISSUE TITLE
Token Action HUD does not handle special characters in actors' names well

### ISSUE THREAD

**Issue by JustinKovacich** [espositos/fvtt-tokenactionhud#171]
When I select one of my PCs I don't get the affiliated token action HUD.  When I check the dev console these are the results:

dnd5e-actions.js:419 Uncaught (in promise) TypeError: Cannot read property 'charAt' of undefined
    at dnd5e-actions.js:419
    at Array.map (<anonymous>)
    at ActionHandler5e._getSkillsList (dnd5e-actions.js:416)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:45)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)

The token's name is Walt but the actor's name is Walter "Walt" Roan.

I have to assume the string parsing for the actor does not properly escape special characters.  Obviously there's a workaround but it probably shouldn't be have like this.

**Comment by JustinKovacich** [comment]
Alright, I might've jumped to conclusions with the title of this, I'm seeing I have a different character that also has the same issue.  Everyone else in game appears to not have this issue.  The other characters name is Gwydgen, so, no special characters, similar error call stack:

dnd5e-actions.js:419 Uncaught (in promise) TypeError: Cannot read property 'charAt' of undefined
    at dnd5e-actions.js:419
    at Array.map (<anonymous>)
    at ActionHandler5e._getSkillsList (dnd5e-actions.js:416)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:45)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)

**Comment by JustinKovacich** [comment]
Looking at the line in JS though it may just be some error handling around verifying the name of the action has characters in it.

**Comment by espositos** [comment]
Hey Justin, sorry it's taken so long to get back to you, it's a busy time. Is it possible the characters have a custom skill? It may be that it is looking in the wrong place on the skill object.

**Comment by espositos** [comment]
@JustinKovacich Hey Justin, I still need your feedback on this. I haven't been able to replicate it locally and would appreciate some ideas.

**Comment by JustinKovacich** [comment]
Hey!  Good call.  Digging into this more, we converted from Roll20 and used the Roll20 Converter to do it.  Roll20 allowed for extra skills to be added, but the converter did not necessarily bring them over correctly, so I think they're blank, extra lines tacked on at the end.

![image](https://user-images.githubusercontent.com/32140377/108710799-83f16b80-74e2-11eb-8400-2eddfb80df16.png)

![image](https://user-images.githubusercontent.com/32140377/108710863-9a97c280-74e2-11eb-9487-4d912b2a7a19.png)

Looks like I can be doing more on my end to not have the broken skills, but suppose it'd be nice to have it not choke on it, either.

**Comment by espositos** [comment]
Thanks :)
I'll have a fix soon

**Comment by espositos** [comment]
I'd appreciate your feedback, feel free to reopen this if it doesn't work for you.

**Comment by JustinKovacich** [comment]
I bumped up to 1.0.0 and tried and it did not appear to work.

**Comment by JustinKovacich** [comment]
Thanks for the quick turnaround with the attempt!  Appears to be the same log:

ncaught (in promise) TypeError: Cannot read property 'charAt' of undefined
    at dnd5e-actions.js:419
    at Array.map (<anonymous>)
    at ActionHandler5e._getSkillsList (dnd5e-actions.js:416)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:45)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)

**Comment by JustinKovacich** [comment]
I do not have permission to reopen.

**Comment by espositos** [comment]
Okay, patched again. I have (hopefully) set it up to print the problematic skill to the console when it encounters it. It would be great if you could a) confirm that the HUD works for your characters and b) post the contents of the error message printed to the console here. I don't know how to give myself an undefined skill and so I'd be curious to see what it looks like.

I'll leave this open in case it's necessary to do further work.

**Comment by JustinKovacich** [comment]
Your patch worked, I have no log to report :)  Thanks for the fix!

**Comment by espositos** [comment]
Great to hear! Any other issues, let me know.

**Comment by JustinKovacich** [comment]
If I were to add a custom skill, does the sheet happen to support it now?

**Comment by espositos** [comment]
Honestly, i don’t know, but if you try it and it doesn’t it would be very helpful to get an export of the problematic actor or their skills on which i could write a fix. If you do add a custom skill, if you click the actor and write the command below in the console, posting the results here, i could work with that:

JSON.stringify(canvas.tokens.controlled[0].actor.data.data.skills)
