### ISSUE TITLE
Hud buttons hide the scene dropdown options when scene is right-clicked

### ISSUE THREAD

**Issue by hafdon** [espositos/fvtt-tokenactionhud#172]
![image](https://user-images.githubusercontent.com/39073287/108241414-d107c300-7119-11eb-9046-9b9e83038e59.png)

foundry 0.7.9
tokenactionhud 0.10.33

**Comment by espositos** [comment]
In the absence of further feedback I am going to close it. But feel free to write a new issue if you have thoughts in the future.
