### ISSUE TITLE
[PF1e] Don't display untrained skills in the HUD

### ISSUE THREAD

**Issue by moorepants** [espositos/fvtt-tokenactionhud#175]
In Pathfinder 1, many skills must be trained, i.e. have spent at least 1 skill point in that skill, before being able to use it. For example, all of the knowledge skills require training. Thus is would be preferable if only the skills one could actually use are shown in the HUD. Right now, all skills are listed and you'd still need to open your character sheet to recall if you can or can't use that skill.

See the "untrained" column here: https://www.d20pfsrd.com/skills/

I'm not sure if the PF1e system exposes this for the needs here, but maybe they already do.

**Comment by espositos** [comment]
Should be fixed in latest patch.

**Comment by moorepants** [comment]
Thanks a ton!
