### ISSUE TITLE
[PF1e] Add Support for Generic Melee, Ranged, and BAB rolls.

### ISSUE THREAD

**Issue by Tarbarian** [espositos/fvtt-tokenactionhud#180]
As a recent addition to PF1e, there is now a generic melee, ranged, and BAB roll function to go along with the generic CMB. It'd be nice to have them in the HUD alongside CMB in the attacks section.

Thank you for the wonderful module and PF1e integration.

**Comment by espositos** [comment]
This should be added. Let me know if there are any issues.
