### ISSUE TITLE
Pf2e target trait detection

### ISSUE THREAD

**Issue by Drental** [espositos/fvtt-tokenactionhud#183]
Hi again, we broke your module once more.

https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/merge_requests/2409

This MR made it so that the current targets conditions & traits (like flat-footed) are now drawn into the attack roll. The way this was added sadly doesn't work with the Token Action HUD. Can you try and get this in?

Thank you for all you are doing for us :)

**Comment by espositos** [comment]
This isn't easy to implement and I'm going to see if stwlam can implement an easier way for the Token Action HUD to take advantage of this. I just don't have the time to focus on working out how it works at the moment, sorry.

**Comment by Drental** [comment]
now works by default due to core changes.
