### ISSUE TITLE
PF2E Consumable Ammo detection and display next to ammo-using attacks

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#184]
Within last 3 weeks, PF2 added support for dropdown of ammo for strikes that use ammo. 

This would be nice to be supported by the Strikes dropdown to display the name and remaining amount of ammo at the end of strikes. 

![image](https://user-images.githubusercontent.com/4083812/111025650-2cae2f00-83ee-11eb-9ad9-ee36a67e7d76.png)

**Comment by espositos** [comment]
![image](https://user-images.githubusercontent.com/14127543/111372815-6bb4dc80-869b-11eb-828d-fd2ba36f45cd.png)
It currently displays it next to the strike name. Is this inadequate?

**Comment by DariusWolfe** [comment]
The issue I run into with this is that, once the ammo goes to 0, TAH will continue to roll the attack die, while showing the out-of-ammo alert. This differs from rolling the attack from the character sheet, which will display the out-of-ammo alert and not roll the attack die.

**Comment by apoapostolov** [comment]
@espositos this is almost invisible depending on the map below. A box with [ 10/10 Arrows ] at the end of the strike would be much more preferred and readable than this small green label.

**Comment by espositos** [comment]
Should be updated in the latest patch, let me know if it's not suitable.

**Comment by apoapostolov** [comment]
It is great, and it even opens the ammo when right-clicking. Thank you very much!

![image](https://user-images.githubusercontent.com/4083812/111453754-972bdb80-871c-11eb-88b2-99c4fc305c34.png)

**Comment by espositos** [comment]
> 
> 
> The issue I run into with this is that, once the ammo goes to 0, TAH will continue to roll the attack die, while showing the out-of-ammo alert. This differs from rolling the attack from the character sheet, which will display the out-of-ammo alert and not roll the attack die.

This will continue to be a problem if the item self-destructs once it's used, but the sheet has the same issue. The HUD will also show a 'no ammo' button which is hopefully suitable.

**Comment by DariusWolfe** [comment]
I should have clarified, I've already turned off ammo self-destruction. The issue is when the ammo count reads 0 (and the ammo isn't destroyed). When clicking from the sheet, it will not roll the die, but when clicking from TAH, it will still roll the die even when there's no ammo.

Partially related, really dig the UI change for ammo, though. I didn't hate the previous way, but this is much more visible.
