### ISSUE TITLE
SW5e R1-A5 TypeError: Cannot Read Property 

### ISSUE THREAD

**Issue by cilise** [espositos/fvtt-tokenactionhud#187]
With SW5e version R1-A5, when clicking on a player token (seems to be ok with NPC sheets), the following error is shown.
This release changed how powers work in the system.  

<img width="374" alt="Capture" src="https://user-images.githubusercontent.com/38544831/111394018-e07e1b80-8687-11eb-9806-54a1ba110ee7.PNG">

**Comment by cilise** [comment]
Sorry about the wonky post, my browser shit the bed during posting.
With the released of SW5e R1-A5, TAH throws an error on player tokens.  

<img width="374" alt="Capture" src="https://user-images.githubusercontent.com/38544831/111393929-b0cf1380-8687-11eb-8e3b-5c8900c55eb4.PNG">

**Comment by Zasshem** [comment]
Hello,

I have open the PR https://github.com/espositos/fvtt-tokenactionhud/pull/188 to fix this issue.
Best regards,

**Comment by espositos** [comment]
I've merged Zasshem's patch, let me know if you have any issues
