### ISSUE TITLE
PF2E: Saving throws not displaying modifiers

### ISSUE THREAD

**Issue by itrase** [espositos/fvtt-tokenactionhud#193]
The top roll is from TokenActionHUD, the bottom is by clicking in the character sheet. The rolls are being calculated correctly, the modifier boxes just aren't showing up.
![Capture](https://user-images.githubusercontent.com/14778681/112320143-1d986e00-8c85-11eb-8956-5051577beac9.PNG)

**Comment by JonWaterfall** [comment]
It seems to happen for monsters, but not for players.

Unless your players are using monster sheets I don't think it shouldn't be a problem.

**Comment by itrase** [comment]
true, but it helps the GM to see what modifiers are effecting the monsters, which is useful. Also, it seems to be a one-line fix in the PF2E rollHandler.
from:
```
   _rollSaveNpc(event, actor, actionId) {
        actor.rollSave(event, actionId);
    }

```
to:
```
    _rollSaveNpc(event, actor, actionId) {
	actor.data.data.saves[actionId].roll(event);
    }

```
would fix it.

**Comment by espositos** [comment]
Thanks, itrase, I'll post a patch
