### ISSUE TITLE
Support for Symbaroum system ready

### ISSUE THREAD

**Issue by Khaali-dev** [espositos/fvtt-tokenactionhud#195]
Hi,

I'm one of the contributors to the Symbaroum system and I've coded support for it in tokenactionhud. 
It works fine - I've used it for several months in my games.
You can find it on the fork  https://github.com/Khaali-dev/fvtt-tokenactionhud

If you're OK I can make a pull request.

You can reach me on discord khaali#8262

**Comment by espositos** [comment]
Hey, yes, I'd welcome a pull request!

**Comment by Khaali-dev** [comment]
Thanks! Pull request done. I didn't change the module version.

**Comment by espositos** [comment]
This is in version 1.0.12. I have some plans for the future, hopefully near-future depending on time, to make the systems independent from the core module. But I'll let you know when and how that happens.
