### ISSUE TITLE
[pf2e] Add Take a Breather macro to utility menu

### ISSUE THREAD

**Issue by JonWaterfall** [espositos/fvtt-tokenactionhud#196]
Hello. Me and the group I play in use the stamina variant rule for Pathfinder 2nd ed. After almost every combat encounter we use the Take a Breather macro to recharge our characters' batteries.

I had a look in the code and it was easy enough to add if we want it to show up for everyone regardless of if the stamina variant rule is enabled or not. I'm new to JavaScript but attempted to see if I could make it so that it only appeared if the stamina variant was enabled. Here's what I have so far:

File: ``pf2e-actions.js``
``_addMultiUtilities()``
![image](https://user-images.githubusercontent.com/28187601/112888335-82fcbc80-90d4-11eb-86c7-1e0e572789ab.png)
``_getUtilityList()``
![image](https://user-images.githubusercontent.com/28187601/112888382-91e36f00-90d4-11eb-9eea-9b63a32a9e53.png)

File: ``pf2e-base.js``
![image](https://user-images.githubusercontent.com/28187601/112888619-de2eaf00-90d4-11eb-8d36-03ac55d80496.png)

I don't know what the stance is on adding variant rule macros, or if there's a better way to check if the variant rule is enabled without requiring a restart of the module, should the GM decide to enable or disable the rule during the session.

**Comment by espositos** [comment]
That's great, thank you, I'll take a look at it.

**Comment by espositos** [comment]
Should be in the latest patch but let me know if you have any issues.
