### ISSUE TITLE
Better Rolls for 5e Integration Broken

### ISSUE THREAD

**Issue by VoltCruelerz** [espositos/fvtt-tokenactionhud#2]
It seems that every time you leave the game and come back to it, you have to set this manually to Core 5e and then back to Better Rolls in order for it to work again.
This seemed fine this morning, so it must have happened in the latest update.

**Comment by espositos** [comment]
There was some bad logic (and might still be some bad logic) in the initialisation of the roll handler. I think I've resolved it. Thanks for reporting it!
