### ISSUE TITLE
WFRP4e Monster native attacks missing

### ISSUE THREAD

**Issue by gravagehulk** [espositos/fvtt-tokenactionhud#201]
I appreciate the Warhammer 4th support, but none of the native attacks show up for the monsters.

I noticed that none of the native attacks of the monsters show up in the Token Action Hud. 

![image](https://user-images.githubusercontent.com/69117052/114212272-411b1400-9927-11eb-8d82-3987cb9e601c.png)

Is there any way other than macros to get things like "Bite" and "Weapon" to show up in the Token action hud?

![image](https://user-images.githubusercontent.com/69117052/114212543-9525f880-9927-11eb-8385-82161c847ac6.png)

Edit: I may be an idiot. I think I see it under "Traits". So, I guess the only thing that's missing for me is "unarmed attack" and "Improvised weapon", which are small buttons under the combat tab on the character sheet.

**Comment by espositos** [comment]
Should be patched in the latest version, under weapons -> basic, but let me know if it's not what you were talking about or could be done differently.

**Comment by gravagehulk** [comment]
I see it and it looks good! Thanks for fixing this so quickly.
