### ISSUE TITLE
Module uses deprecated parameters in PF2e

### ISSUE THREAD

**Issue by sirrus233** [espositos/fvtt-tokenactionhud#208]
When rolling a strike from the HUD in the PF2e system, I get a warning in the log:
`You are using the old roll parameters. Use roll({event, options?, callback?}) instead.`

Rolls otherwise seem to work fine, but this could lead to incompatibility down the line, so I figure good to file an issue here.

**Comment by espositos** [comment]
Thanks for reporting it sirrus. I don't have a lot of time at the moment for this but I will keep an eye on it. Hopefully I'll find some time soon. If it really breaks, please let me know and I'll fix it as a priority.
