### ISSUE TITLE
PF2E Saving Throws

### ISSUE THREAD

**Issue by Nat-Faeeria** [espositos/fvtt-tokenactionhud#217]
Hello,
This is not critical, but the PF2e module has changed its data format on some stuff, including the Saving Throws.
They now appear as PF2E.SavingsWill and such in the Token Hud. I think it might be fixed by fetching PF2E.SavingsWill.value, but not sure.

**Comment by Cosmic-Lattee** [comment]
It isn't just saving throws. When you do group checks by selecting all the tokens it looks like this now: 

![image](https://user-images.githubusercontent.com/24766235/116870139-90c3c700-abd7-11eb-880e-34eb66692e47.png)
 
Abilities are also messed up:

![image](https://user-images.githubusercontent.com/24766235/116870178-a46f2d80-abd7-11eb-9f4d-87646f2e5851.png)

**Comment by espositos** [comment]
Thank you for reporting this. I think Drental has submitted a pull request which should resolve this, but if it's not resolved please let me know.

**Comment by Drental** [comment]
should be all done now :)
