### ISSUE TITLE
BetterRolls5e clicks not registering (0.6.5)

### ISSUE THREAD

**Issue by MerrickCat** [espositos/fvtt-tokenactionhud#22]
I just updated to beta version 0.6.5. Now, my clicks are not triggering any actions/rolls. The mouseover still opens up the HUD and sub-menus, but I can't roll anything from the HUD. 

It's possible that the timing is coincidental and that the underlying cause is incompatibility with another module. But I'm not aware of anything.

Edit: I believe that it's an incompatibility with the Better Rolls module, because it rolls to the Core 5e roller correctly.

**Comment by espositos** [comment]
I'll check this out later. It could be that Better Rolls has updated their API

**Comment by espositos** [comment]
I think this is a bug on BetterRolls end with the 0.6.5 patch. I'll wait for Red Reign to update for 0.6.5 and then if the issue persists I'll take another look.

**Comment by espositos** [comment]
I think the bug is fixed and at least for me BetterRolls is working with the HUD again. Closing this for the moment, but feel free to report if you have more issues with this.
