### ISSUE TITLE
Compatibility with 0.8.x

### ISSUE THREAD

**Issue by rmasoni** [espositos/fvtt-tokenactionhud#230]
Token Action HUD doesn't work with the new releases, and I miss it a lot!

**Comment by Battenhatch** [comment]
Yes, this little wonder needs some 0.8.x love :)

**Comment by ksanchez1987** [comment]
Agreed.  It's absence almost is enough to make me revert to 7.* just so i have it... Makes running my games so much easier.

**Comment by yahavatar** [comment]
TAH is a wonderful module. I miss it too!

**Comment by espositos** [comment]
So the changes for 0.8.x are breaking as far as I understand, which means that fixing it for 0.8.x could prevent it working on 0.7.x. Thanks to yahavatar, I think (read: hope) I can support both simultaneously, but it might be a bit of a rough transition if I have fucked up. Anyway, it should work for 0.8.x now, but let me know if you have any issues.
