### ISSUE TITLE
Token Action HUD 1.20.0 5E 1.2.4, 0.7.10, some characters don't show HUD at all

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#238]
This is a weird effect I noticed in my game after several updates of Token HUD since the last session. Some PC actors don't show Token HUD at all, while others show it. The behavior is very consistent.

There's no such problem in PF2 and seems to affect my 5E worlds only.

**Comment by espositos** [comment]
It's probably related to me trying to fix the HUD for 0.7.x and 0.8.x, sorry :(. Any errors in the logs?

**Comment by gioppoluca** [comment]
Same for me
