### ISSUE TITLE
HUD not appearing 

### ISSUE THREAD

**Issue by seravera** [espositos/fvtt-tokenactionhud#239]
Love this mod! I’ve got it working great on a friend’s server and recently got my own license and server. In my new world, the HUD only loads for actors who don’t have any spells. Doesn’t matter if I bring in spells from SRD or DDB (I’m running DND 5e). Even dropped in a starter hero, the HUD does not appear for them. If I delete all the spells off a sheet, then the Token HUD appears.
I appreciate any tips on what to check on my side or if this is a compatibility issue.

**Comment by p-becker** [comment]
Which FVTT and module version are you using?
And can you copy any errors from the javascript console (F12)?

**Comment by tophatraptor** [comment]
Using 0.8.5 beta, version 1.0.20 for Token Action HUD, I get the following error in console:

`dnd5e-actions.js:633 Uncaught (in promise) TypeError: actor.effects.entries.some is not a function
    at dnd5e-actions.js:633
    at Array.forEach (<anonymous>)
    at ActionHandler5e._addConditionsSubcategory (dnd5e-actions.js:629)
    at ActionHandler5e._getConditionsList (dnd5e-actions.js:559)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:40)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)`

**Comment by espositos** [comment]
So I take it it works now? Closing this for the moment.

**Comment by seravera** [comment]
Can confirm I can view the Hud for all characters, even the wizards, after the update. Thank you!

**Comment by zarmstrong** [comment]
This still seems to be happening. There's another player in my game that is experiencing this. Server is using 1.0.22 on 0.7.9.

Additionally, this user also saw another users token action hud, despite having no permissions for that user. 

Sorry I can't provide more details, it's a player at another game I'm playing in and he's not tech savvy enough to get anything from the console
