### ISSUE TITLE
Enhancement: More translation options

### ISSUE THREAD

**Issue by HonzoNebro** [espositos/fvtt-tokenactionhud#24]
There are some things in the HUD that still need translation, I'm using the file I created on https://github.com/espositos/fvtt-tokenactionhud/pull/23 for the screencaps

Item names are shown properly (I have some in english)
![image](https://user-images.githubusercontent.com/5500663/86592636-241a7480-bf94-11ea-8906-42f152f55400.png)

Spell level is missing
![image](https://user-images.githubusercontent.com/5500663/86592690-398f9e80-bf94-11ea-87cb-f426926ee64d.png)

All of the abreviations here
![image](https://user-images.githubusercontent.com/5500663/86592814-6e035a80-bf94-11ea-9933-78e92a544437.png)

All of the abreviations here
![image](https://user-images.githubusercontent.com/5500663/86592879-85dade80-bf94-11ea-82fc-5b405a545ee2.png)

And somehow it is translating "Save" to "Guardar" (which is correct, just, not here, it should be "Tiradas de salvación", or something shorter 😄 )
![image](https://user-images.githubusercontent.com/5500663/86593004-c0447b80-bf94-11ea-8560-3a111c665cf3.png)

**Comment by espositos** [comment]
Noted. I'll try to add them :)

**Comment by Sebastian5477** [comment]
Hello, I have the same request.  Would like the ad to be displayed completely in German.  But all designations for the SKILLS remain in English.
Greetings Sebastian

**Comment by espositos** [comment]
Some of the translations are drawn from localizations for the the various systems, so I will try to go through the code and make them all reliant on the local references

**Comment by espositos** [comment]
Sorry, for everyone who has contributed, could you please take a look at the localization files on the develop branch:
https://github.com/espositos/fvtt-tokenactionhud/tree/develop/lang
I've removed the system-specific language trees and I went through the program and tried to remove everywhere I was reliant on other systems' localizations for terms. I've also added more terms for all of the systems in general. It would be really helpful if you could go through your respective contributions and bring them up to date. I'm also sorry for not having a clear plan for internationalization in the first place!

**Comment by HonzoNebro** [comment]
I don't see anything that needs changing in the spanish file

**Comment by espositos** [comment]
That's fine, if the Spanish file covers what you need and it works with the most recent version, all good :)
Thank you for contributing!

**Comment by espositos** [comment]
Closing for now, although further internationalization is always welcome.
