### ISSUE TITLE
0.8.6, dnd5e 1.3.3: The document@_id property is depreciated in favor of Document#id or document#data#_id

### ISSUE THREAD

**Issue by Brimcon** [espositos/fvtt-tokenactionhud#243]
I get this warning spammed to the console about 30 times upon clicking on a token:

![image](https://user-images.githubusercontent.com/7198283/120248588-abb44600-c22c-11eb-8b30-38a0c6303946.png)

**Comment by KaiZano** [comment]
I haven't checked console but the module does not work on my game either. (0.8.6)

**Comment by Th3Rom3** [comment]
I can confirm this behaviour in my DnD 5e system anmd 0.8.6. The module otherwise seems to work fine but during normal use a few thousand warnings accumulate in few minutes.

**Comment by espositos** [comment]
Should be fixed, but let me know if not
