### ISSUE TITLE
0.8.6 PF2 issue: HUD does not show up for Spontaneous casters when we toggle spells as Signature Spells

### ISSUE THREAD

**Issue by yoshisman8** [espositos/fvtt-tokenactionhud#248]
This is specific to The Pathfinder 2nd Edition system (Version 2.0.3.5912) using Token Action HUD (version 1.0.22). When toggle an Actor's Spells to be signature spells (The star icon on the spell itself)
Doing so triggers the following error on the console and causes the HUD to not show up for that token anymore.
![image](https://user-images.githubusercontent.com/4214215/120666423-93297300-c45a-11eb-8192-32ddaabb85bd.png)

**Comment by Cosmic-Lattee** [comment]
I am having the same issue. Happens on a fresh game with no modules as well.

**Comment by PennDavies** [comment]
Same. Trying to kludge around this for the 13th level Sorcerer will be a pain. :)

**Comment by espositos** [comment]
This should be resolved in the latest patch but let me know if it's not.
