### ISSUE TITLE
1.0.25 - 5e - FVTT 0.8.6 - Token Action HUD buttons not working

### ISSUE THREAD

**Issue by GrumpyGriffon** [espositos/fvtt-tokenactionhud#256]
In the latest release (about an hour ago), the buttons are not working.  I get a console error, though:

![image](https://user-images.githubusercontent.com/85559626/121185829-5f858900-c85e-11eb-84ba-74e0ba89c03d.png)

I have unloaded all other modules, to make sure this wasn't a conflict.

**Comment by maxphoenix01** [comment]
Same here. The buttons aren't doing anything

**Comment by PointFrankRange** [comment]
I am encountering the same issue.  The HUD shows up as expected, but when clicking on any of the buttons nothing happens.

**Comment by TSBeebeJ** [comment]
Same issue for me.  Buttons are present but not working.  I also unloaded all other modules.

**Comment by espositos** [comment]
Should be fixed, please let me know if you still have issues.

**Comment by GrumpyGriffon** [comment]
Thank you @espositos !  My players and I love this plugin so much.  I've re-tested with 1.0.30, and it's working great.  We appreciate your hard work!

**Comment by PointFrankRange** [comment]
Confirmed working for me now as well.  Thanks you.
