### ISSUE TITLE
FVTT 8.6 PF2e 2.1.1 Spells don't roll from the HUD

### ISSUE THREAD

**Issue by dnotar** [espositos/fvtt-tokenactionhud#260]
FVTT 8.6 PF2e 2.1.1

Hello, 

The spells that appear in the HUD do not generate text in the chat that can be clicked to roll. The spell appears but clicking save or damage does nothing.

**Comment by gnlatgh** [comment]
FVTT 8.6 PF2e 2.1.1 Token Action HUD 1.0.30

confirmed. Spells rolled from token action hud appear in chat as normal but once you click on the chat buttons, nothing happens, not even errors in console.

![image](https://user-images.githubusercontent.com/85176277/121312468-b2fee200-c905-11eb-8b77-8ee1235acbc3.png)

**Comment by espositos** [comment]
Unfortunately there is nothing I can do about this at the moment, it has to do with the code PF2E uses to send the data to chat. I am trying to raise it with the PF2E devs.

**Comment by FadedMaster** [comment]
I'm not sure if it helps, but when weapons, potions, and the like and clicked on and this info is sent to the chat, those links still work.

**Comment by espositos** [comment]
I think this is fixed by Drental's latest PR, but reopen this if necessary.
