### ISSUE TITLE
Module will not initialize

### ISSUE THREAD

**Issue by trdischat** [espositos/fvtt-tokenactionhud#261]
Running module version 1.0.30 on FVTT 0.8.6 and dnd5e 1.3.3 with all other modules disabled, the Token Action HUD module fails to initialize with this error:

![chrome_SCKgMPt9sO](https://user-images.githubusercontent.com/52774325/121343429-82a04f00-c8d7-11eb-9275-0a85d415f1f2.png)

**Comment by espositos** [comment]
This should be resolved but let me know if it persists
