### ISSUE TITLE
Cannot bulk apply conditions

### ISSUE THREAD

**Issue by spaceman02-ops** [espositos/fvtt-tokenactionhud#266]
I cannot apply conditions to multiple tokens when they are all selected. I get the following error:
![image](https://user-images.githubusercontent.com/60070162/121612621-60661880-ca20-11eb-8088-f5def0e1bdd6.png)

**Comment by spaceman02-ops** [comment]
Just noticed that this is fixed by BenBarbour's pull request.

**Comment by espositos** [comment]
I've merged their changes, but feel free to reopen this if the issue persists.
