### ISSUE TITLE
FVTT 0.8.6, 3.5e SRD 0.93.2, HUD doesn't show up for PC and NPC

### ISSUE THREAD

**Issue by duebbers** [espositos/fvtt-tokenactionhud#268]
I have the same problems with 3.5e SRD, others had with PF2  # # #242 
I updated to TAH 1.0.34 but no change

Maybe 3.5e SRD has changed the Spellbook-Properties? 
I get the following errors in the console if I click on a character/NPC (even if they don't have any spells) :
![grafik](https://user-images.githubusercontent.com/18099824/121800179-8cf07f00-cc30-11eb-980f-fac1ab2a08eb.png)

**Comment by espositos** [comment]
Thanks for reporting it. I'll look into it. I guess this will happen with every system as they migrate over to 0.8.

**Comment by Rughalt** [comment]
This should be fixed in #270 !

**Comment by duebbers** [comment]
Thank you!!
works fine again with Foundry 0.8.7, 3.5e SRD 0.93.3 and TAH 1.1.0
