### ISSUE TITLE
FVTT 0.8.7, SWADE 0.19.4, TokenActionHUD 1.10, Better Rolls 2 for SW 2.34 - Items don't work for BR2SW

### ISSUE THREAD

**Issue by zk-sn** [espositos/fvtt-tokenactionhud#272]
Items don't work for Better Rolls 2 for Savage Worlds
The swade-br2sw roll handler is calling **game.brsw.create_item_card_fromid** instead of **game.brsw.create_item_card_from_id**

I will submit a merge request which fixes this.

**Comment by espositos** [comment]
Thank you very much for the report and the subsequent PR 💌
