### ISSUE TITLE
HUD Overlay not updating with changes to NPC/Monster

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#28]
When I update NPCs attacks that I have imported from compendiums the changes don't show up in the HUD. Specifically, Since only the Strikes have their actual values displayed, they are the only ones I can see. The changes DO actually work however. 
In the image below the War Flail should be +12 (which it does roll appropriately) but the HUD only displays the original +10. Also, completely new strike entry don't display that data at all but do roll correctly. 

Also, any new, custom created NPC shows up just like the new entry (undefined) but does in fact work. 

I believe you're still working on incorporating it for NPC so I just thought I would list this. 

![TokenHUDNPCUpdate](https://user-images.githubusercontent.com/65833146/86873041-688c3a00-c092-11ea-84ed-25cd633bb757.png)

**Comment by espositos** [comment]
Good to know. I'll have to check the issue.

**Comment by espositos** [comment]
Should be fixed in the latest release, although the latest release probably has reintroduced more bugs.
