### ISSUE TITLE
Issue: Not working on 0.8.7?

### ISSUE THREAD

**Issue by CalabC** [espositos/fvtt-tokenactionhud#283]
My Foundry is set to 0.8.7 (Latest)
Playing on DnD5e 1.3.5 (Latest)
Token Action HUD 1.1.2 (Latest), and it's the only module

It's not working right, whenever I put anything in the actor's inventory it doesn't show.

https://user-images.githubusercontent.com/76928388/122688079-1af7d700-d1e8-11eb-8aad-be85ea55fc89.mp4

**Comment by benbarbour** [comment]
Equip the item (little shield icon on the inventory line).

**Comment by CalabC** [comment]
Yep! Your right, there was a mod conflict with "Item Macro", I tested it out on a new world with just these two mods. Token Action Hud is now working, thank you!
