### ISSUE TITLE
D&D 5e Bonus Action, Action, Reaction, Special symbols missing

### ISSUE THREAD

**Issue by CrimWolfe** [espositos/fvtt-tokenactionhud#292]
I apologize if this was mentioned as I could not find it. I know there are certain issues right now being worked on with spells and skills, but I am wondering if the option to have special symbols next to certain actions, features, spells are gone due to an error or if it is going to be lacking this feature.

It was helpful for me to separate certain weapons that I had made for bonus actions (plus sign) or say a quick reminder that I have Shield to use as a reaction spell (think it was a lightning bolt symbol). Even Divine Smite as a special had a little star next to it. Thanks!

**Comment by benbarbour** [comment]
Sorry again. I'm sorry; I'm not used to not having unit tests covering my butt. I really should've tested more before making a PR, even though I don't intend on using that mode myself. Lesson learned!

**Comment by CrimWolfe** [comment]
Hey, no worries! I love this module as do my players. You've done a fantastic job!. Hiccups happen. :) Thank you for all the hard work done!
