### ISSUE TITLE
Cantrips Not showing up in 5e 

### ISSUE THREAD

**Issue by fatigues65** [espositos/fvtt-tokenactionhud#297]
I believe that a fix to address spells not showing up in 5e was added earlier today. That _sort of worked_. Problem, it only is showing spells of level 1 and up on the HUD. It is **not showing cantrips**.

Seeing as those are the go to attack spells for most Wizards... when they aren't doing anything else that's flashy -- that's a problem.

**Comment by roi007leaf** [comment]
doesnt happen to me
![image](https://user-images.githubusercontent.com/17231451/123591226-5e5bd200-d7f4-11eb-8d10-d1124833b91e.png)

**Comment by Fridan99** [comment]
In my game I can see the cantrips with the recent update.
![screenshot](https://user-images.githubusercontent.com/86131373/123615724-7ab03c80-d7fd-11eb-81d4-9241268f90e4.jpg)

**Comment by fatigues65** [comment]
Well, I'm not making it up: 
![image](https://user-images.githubusercontent.com/80716531/123641897-bbee1f80-d7f0-11eb-80db-15164c15718e.png)

**Comment by fatigues65** [comment]
From the above cases where it is working, it appears to be a case of innate racial casting sources in one case, and a druid in the next.

Is there something wrong or different in the way it is capturing wizard spells of 1-9 but not cantrips?

**Comment by benbarbour** [comment]
Hmmm, if you don't mind posting the actor's data (right click on the Actor in the sidebar, press "Export Data", save the file, and attach it to a response here) I can take a look, but I can't replicate this. I tried a few different combinations of things, including setting the Preparation Mode to "Innate Spellcasting" and the cantrip still always shows up. Are the spells in question set up to use limited resources of some kind, and does the character have enough of those resources?

**Comment by fatigues65** [comment]
I'm not sure. It's possible I am doing something totally noobish and overlooking the obvious. I'd say "Hell NO I'm not that dumb!"... except, there is a _distinct_ possibility I might be _**precisely**_ that dumb.  :)

[fvtt-Actor-raistlin-majere.zip](https://github.com/espositos/fvtt-tokenactionhud/files/6728392/fvtt-Actor-raistlin-majere.zip)

**Comment by fatigues65** [comment]
Ahhhh. I think this needed to be set to "at-will" within the spell. Let me check *winces*

**Comment by fatigues65** [comment]
Yes. They needed to be set to always prepared .When they are  - they are showing up. I apologize for wasting your time.

**Comment by benbarbour** [comment]
Well, something weird is still happening on your end, because they _don't_ need to be set to "Always Prepared" for me. They should up in the "At Will" subcategory (but still under "Spells") if they are "Innate Spellcasting", but if I just set them to "Prepared" then they still show up, regardless of whether or not they are marked prepared or not. I believe this is by design.

**Comment by benbarbour** [comment]
Or something could be weird on my end, I guess!
