### ISSUE TITLE
Token HUD not showing up

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#299]
The Token HUD doesn't show up now for me suddenly. I get these errors when the world loads but otherwise not getting any errors when clicking tokens etc
Ruleset: PF2e
Foundry Ver: "Stable" 8.8
Host: Forge VTT

![image](https://user-images.githubusercontent.com/65833146/123737084-35b8f400-d857-11eb-97cf-e62fc360e4e5.png)

**Comment by alexsj2315** [comment]
Same issue for me here. HUD suddenly not appearing on new worlds and doesn't appear in module settings list.

Ruleset: DnD 5e
Foundry Ver: "Stable" 8.8
Host: Forge VTT

**Comment by williamsfl350** [comment]
Getting the same issue as well. Also on Forge-VTT. Might be related to that.

Ruleset: PF2e
Foundry Ver: "Stable" 8.8 and also tested on 8.7
Host: Forge VTT

**Comment by Khybersghost** [comment]
Maybe Forge was acting up yesterday. I did have some other Forge related errors and checking again just now it seems to be working for me.

**Comment by williamsfl350** [comment]
After talking with the Forge guys on Discord, it looks like it was a browser cache/setup problem. They seem to have fixed the issue.

**Comment by espositos** [comment]
Really glad to hear it, thank you!
