### ISSUE TITLE
Cantrips Don't Show in Spell Section

### ISSUE THREAD

**Issue by Dumbhuman** [espositos/fvtt-tokenactionhud#3]
Currently the Spell section only shows spells that are marked as prepared, but Cantrips can't be prepared on any of the character sheets that I've seen, so perhaps they should be placed into their own category or otherwise be somehow flagged as always prepared by Token Action HUD so that they'll show in the Spells section.

**Comment by espositos** [comment]
Hey, I'm happy to reconsider this, so let me know if you have strong feelings about it, but all spells should be able to be set as prepared via this checkbox:
![image](https://user-images.githubusercontent.com/14127543/85660659-2c320480-b6b6-11ea-9212-fc1ef81953b3.png)

This was to allow spellcasters to import all spells into their spellbook so they have an overview without returning to the PHB/compendium/etc., and then be able to choose which ones they are really casting based on what is prepared.

**Comment by Dumbhuman** [comment]
Ah, I missed that because I was only looking at the spell lists on the character sheet which have checkboxes to prepare leveled spells, but not cantrips.  It seems a little counter-intuitive to how the DND 5E rules work, because having access to a cantrip one can't always cast is a rare condition (likely tied to losing an item) so I'd expect cantrips to default to prepared and only be able to be unprepared in the exceptional cases (for instance, a Pact of the Tome Warlock temporarily separated from their Book of Shadows).

My primary use for Token Action Hud however is to most easily run enemies as a DM without needing their character sheets up or having to heavily customize them first, so the option to have cantrips simply show on the HUD without editing each cantrip individually first would certainly be most welcomed and I'm sure others out there would appreciate it as an optional setting at the very least (if not default behavior).

**Comment by espositos** [comment]
It's something I hadn't considered, I'll implement the choice as a setting.

**Comment by espositos** [comment]
It's implemented as an option in 0.2.0. The default setting is to show all non-preparable spells, as you wanted. Thanks for suggesting it! Any issues, let me know.
