### ISSUE TITLE
HUD has gone rogue ;)

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#30]
The HUD now displays really large buttons which go vertically down the screen. Not getting any console error that I can see
![New TokenHUDerror](https://user-images.githubusercontent.com/65833146/87095055-e49e9300-c1f4-11ea-8efb-e33b8e5dae12.png)

**Comment by espositos** [comment]
I moved the CSS and forgot to update it in the module.
