### ISSUE TITLE
PC damage buttons not working

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#31]
Thanks for fixing the layout issue. :)
The Damage button in the strikes tab of the HUD doesn't work for PCs, but works fine for NPCs.
Getting this error in console
![HUDDmdbuttonerror](https://user-images.githubusercontent.com/65833146/87099704-4d8b0880-c1ff-11ea-8bc0-a075fdb00093.png)

**Comment by espositos** [comment]
Thanks for reporting it :) Should be fixed in the 0.4.3 update.
