### ISSUE TITLE
PF2 Enhancement: Manual change of focus and spell slots

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#32]
Token Action HUD already supports PF2 spellbooks, and recognizes level slots and focus points to display their number in the header of each action list inside Spells. This can be taken a step further to add a system block at the beginning of each spell level or spellbook that allows the user to manually change focus points remaining or spell slots remaining per level inside a spellbook.

**Why this is needed?** Unlike 5E, PF2 doesn't yet have a step before posting a spell in the chat that allows to consume that spell or spell slot or focus point related to that spell. This means while the player can enjoy the Action HUD he must go into the inventory to remove the spell slot. Naturally players forget to dot his in their own favor. 

**How it looks?** For any spellbook level that uses focus point or spell slots, create a brick that contains icons to + and - a value between it. This way the user can manually tweak the value without opening their character sheet.

**What about prepared spells?** Using prepared spells is a bit different and can be done by adding a X button inside the brick of a spell so the player consumes it manually after he posts the spell in the chat to cast it.

**Comment by espositos** [comment]
In the latest release, thanks for your help, Apo
