### ISSUE TITLE
PF2 Enhancement request for spell expenditure 

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#33]
Not sure if this is possible or not. It would help minimize the need to open the character sheet for spell casters if any spell they clicked on in the HUD was expended on click. 

For prepared casters, this would have to interact with the expend spell function of the character sheet to strike through the spell. 
![Strikethrough (Prepared)](https://user-images.githubusercontent.com/65833146/87177937-4a405d00-c291-11ea-837f-d26f756340bf.png)

For spontaneous spell casters, it would deduct from spells / day of that level. 
![Spontaneous](https://user-images.githubusercontent.com/65833146/87177997-63490e00-c291-11ea-885a-0d981cdea1be.png)

**Comment by espositos** [comment]
This and Apo's request are related, but I urge you both to press the PF2E devs to implement these things as API functions for scripters to use. It will make future development and maintenance much easier.

**Comment by apoapostolov** [comment]
@espositos Can you confirm that API for this does not exist right now? If so, I will post an issue on the PF2 issue board. But I can benefit from confirmation that such API doesn't exist and needs to be added.

**Comment by espositos** [comment]
I am almost certain it doesn't. The sheet calls a method called _setExpendedPreparedSpellSlot directly, which relies on information in the character sheet html.

**Comment by apoapostolov** [comment]
From my test today it seems to be sufficient.

**Comment by espositos** [comment]
In the latest release.
