### ISSUE TITLE
Token Action Hud not saving new position. 5E

### ISSUE THREAD

**Issue by aestrada4355** [espositos/fvtt-tokenactionhud#34]
Foundry 0.6.5
D&D 5E 0.93
Token Action Hud 0.4.5

Token action hud does not update HUD position, though no console errors are present.
Confirmed in existing and new campaign world with 0 mods enabled apart from Token Action Hud.

![image](https://user-images.githubusercontent.com/67869538/87218449-cafa6a00-c320-11ea-8bb5-900b59502f8d.png)

**Comment by espositos** [comment]
Should be fixed in latest release
