### ISSUE TITLE
Enhancement: Recharge from within HUD

### ISSUE THREAD

**Issue by Dumbhuman** [espositos/fvtt-tokenactionhud#35]
Right now the HUD displays the text "(Recharge)" after features that need to recharge, but it would be amazing if there was a way to roll that recharge from within the HUD rather than having to open the character sheet.  Maybe middle mouse button on the Recharge text?

**Comment by espositos** [comment]
Ah, there should be. It was implemented so if you click on something with (recharge) it rolls the recharge roll instead, but I'll look into why it's not working.

**Comment by espositos** [comment]
Ah, I realised I only implemented it for the Core roller. I'll expand it to the Minor QOL and Better Rolls handlers.

**Comment by espositos** [comment]
Done, should work for all of them now. You just normal click a (recharge) item or feat and it should roll the recharge check.
