### ISSUE TITLE
Minor PF2 polish on spells

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#36]
* Rather than Level 0 Spells, call Level 0 spells as Cantrips
* Prepared Spells Level 0 (Cantrips) do not need [-] button as while they are prepared they are not exhausted and can be cast unlimited times. This is only true for Level 0 (Cantrips) spells. Level 1+ need to have the [-] button.

**Comment by espositos** [comment]
in the 0.4.11 patch
