### ISSUE TITLE
Bug: Healing treated as damage (using Better Rolls as HUD roll handler and Minor QOL to apply effects)

### ISSUE THREAD

**Issue by Dumbhuman** [espositos/fvtt-tokenactionhud#37]
If I use Better Rolls as the HUD roll handler, target a token, and cast Cure Wounds through the Token Action HUD, hit points are subtracted from the targeted token instead of added to them.

Casting the same spell through the character sheet properly adds hit points for healing.  If I switch the HUD roll handler to Minor QOL or Core 5E, the healing is also treated correctly and adds hit points to the targeted token.  Only using Better Rolls through the HUD seems to cause the problem.

**Comment by espositos** [comment]
For the moment I think this is a bug with either Minor QOL for failing to detect BetterRolls' handling of healing spells, or BetterRolls' implementation of healing spells. I don't think I can do anything about it, but I will bug both authors for an explanation.

**Comment by espositos** [comment]
![image](https://user-images.githubusercontent.com/14127543/87396202-c2b95d80-c5b2-11ea-8b39-04e3d5d8eb7c.png)

**Comment by espositos** [comment]
Seems to be fixed
