### ISSUE TITLE
Enhancement: Prevent activation of a feature if no uses remain.

### ISSUE THREAD

**Issue by Dumbhuman** [espositos/fvtt-tokenactionhud#38]
If I try to activate a feat with 0/1 uses remaining through the Tidy 5E character sheet, I receive an error across the top of the scene reading "No charges left" and nothing is sent to the chat window for that feat.

It would be very nice if Token Action HUD could replicate that behavior rather than sending the feat to chat as though it had uses left.

Also it would be nice if the [2/2] style of notation after an item with limited uses would display [0/2] when all uses are expended.  Currently it disappears if no uses remain, but showing it as [0/2] would be a nice quick visual reminder that the resources have been all used up.

**Comment by espositos** [comment]
After discussing this on Discord, the 'No charges left' is a feature of Minor QoL and can be taken advantage of in the HUD if you have Minor QoL as your roll handler (in settings). But the charge notation sometimes goes missing which is definitely a bug.

And I can add a setting to show items which are used up.

**Comment by espositos** [comment]
In the next patch
