### ISSUE TITLE
Enhancement: Display spells from Magic Items module

### ISSUE THREAD

**Issue by joshjlewis93** [espositos/fvtt-tokenactionhud#39]
The Magic Items module allows you to add spells on magic items - however, since they're not part of the normal spellbook, they aren't registered anywhere.

I have no idea how feasible it is, but it would be really neat if TAHUD could somehow pick up on the existence of those spells and display them somewhere, possibly with an indicator of what item they came from.

**Comment by espositos** [comment]
I'll take a look into it.

**Comment by espositos** [comment]
I've implemented it, but let me know if there's something that it should do and doesn't do, or about any bugs.

**Comment by joshjlewis93** [comment]
Works great so far! I have noticed one issue so far - clicking a spell on the HUD that spends charges on the item does not spend them if using Better Rolls as the roll handler.

The following error pops up:
Uncaught (in promise) TypeError: this.preRollHandlers is not a function
    _magicItemMacro xyz/modules/token-action-hud/scripts/rollHandlers/dnd5e/pre-magicItems.js:34
