### ISSUE TITLE
Strange Behavior when using Minor Quality of Life and BetterRolls

### ISSUE THREAD

**Issue by ZBell** [espositos/fvtt-tokenactionhud#40]
Hello, I've noticed some odd behavior when using Minor Quality of Life in conjunction with BetterRolls and Token Action Hud.  MQoL recently added the ability to display the Token name in chat messages, rather than the Actor name.  It seems to work perfectly with BetterRolls when rolling from the sheet, the rolls are displayed correctly and the names display the Token name.  However, when pulling the BetterRolls item down to the Macro bar, or rolling from the Action Hud, it doesn't display the correct name.  I think this comes down to the way BetterRolls is finding the proper Actor, but I'm not sure.  I've attached a screenshot that hopefully better illustrates what I mean.  In the screen shot when Richard was selected Action Hud rolled as Howard, when Howard was selected it rolled as Carl, and when Carl was selected it rolled as Richard.  I can't seem to find how or why it's selecting the token's name.  I'm happy to do more specific tests or get you more info if you need.  Thanks!
![StrangeBehavior_BR_MQOL_TAH](https://user-images.githubusercontent.com/4707545/87480454-5dd62580-c5fb-11ea-965b-4acc0456d33e.png)

More info I just noticed.  When dragging a BetterRolls macro to the bar it uses this syntax,
BetterRolls.quickRollById("R4UI2BDw4xiqlakQ", "TjppHCK64yTIB5sF");
Where the first value is the actor ID, and the second is the item ID I think. If you do this instead,
BetterRolls.quickRollByName("Howard", "Bite");
Using the Token name and the item name it seems to work fine.  I don't know if there's a way to make ActionHud have an option to have its macros use the Token name of the selected token instead of the Actor name, or if this is something that should be brought up with the author of BetterRolls.

**Comment by espositos** [comment]
Ah, so what BetterRolls is doing is selecting an actor based on the actor._id, and because there are multiple tokens with the same base actor._id, you basically get a random actor back, and from there it gets the name. I'm not immediately sure what the solution is, but I think you should mention it to Red Reign at BetterRolls.

**Comment by espositos** [comment]
Ah, I found the issue on my end. There is a better method I could be using. Should be fixed in 0.4.12

**Comment by ZBell** [comment]
Awesome, thanks!  Should I still bring it up to RedReign?
