### ISSUE TITLE
Typo: In module settings, correct "actiosn" to "actions"

### ISSUE THREAD

**Issue by Merudo** [espositos/fvtt-tokenactionhud#44]
The word "actiosn" should be corrected to "actions".

Line that should be corrected:

https://github.com/espositos/fvtt-tokenactionhud/blob/0662a1f4e4efd616843bb586f07160ce17340e6f/lang/en.json#L79

**Comment by Merudo** [comment]
PR #45 fixes this.

**Comment by espositos** [comment]
Thank you for the PR!
