### ISSUE TITLE
"Feats" button should read "Features"

### ISSUE THREAD

**Issue by justinrpurdy** [espositos/fvtt-tokenactionhud#46]
This can be confusing for players, as "feats" are a separate thing.

**Comment by espositos** [comment]
Which system are you talking about?

**Comment by espositos** [comment]
Is this PF2E? And whichever system you're talking about, is there something which I should label as 'feats' instead?

**Comment by espositos** [comment]
Implemented for PF2E, hope that's the system you meant.

**Comment by justinrpurdy** [comment]
My fault, I had been referring to 5e. Thanks for the quick response though!

**Comment by justinrpurdy** [comment]
Regarding whether something else should be labeled "Feats" - in the context of a token hotbar, probably not.
