### ISSUE TITLE
Better Rolls for 5e Compatability

### ISSUE THREAD

**Issue by bibicvc** [espositos/fvtt-tokenactionhud#48]
Better Rolls allows you to roll with several modifiers - none for default, shift for advantage, ctrl for disadvantage, and alt for an secondary roll that you can customize.

Currently, Token Action Hud will always use the secondary roll as if alt is pressed. This secondary roll will still interact appropriately with shift and ctrl but the default roll cannot be activated. Holding alt has no effect. The intended functionality would be for a secondary toll to only be activated if alt is pressed.

**Comment by espositos** [comment]
Implemented in 0.5.0, but let me know if something isn't working as expected
