### ISSUE TITLE
Pact Magic Upcasting

### ISSUE THREAD

**Issue by Alexis-Grimm** [espositos/fvtt-tokenactionhud#5]
When I have no normal 2nd level spell slots remaining 2nd level spells do not display even though I have 2nd level pact slots remaining, this also applies to lower level spells (I have 2nd level pact slots, but no normal spell slots remaining, level 1 and level 2 spells do not display in the action hud)

**Comment by espositos** [comment]
I think this is fixed, but if you have any problems let me know.
