### ISSUE TITLE
Unable to use HUD on any tokens in FVTT 0.6.5

### ISSUE THREAD

**Issue by astraldreadnaught** [espositos/fvtt-tokenactionhud#50]
Module not functioning with any tokens in 5E.  Regardless of whether there are other modules installed or not, this error in console when any token is clicked:

dnd5e-actions.js:121 Uncaught (in promise) TypeError: Cannot read property 'abilityActivationTypes' of undefined
    at ActionHandler5e._getActiveEquipment (dnd5e-actions.js:121)
    at ActionHandler5e._getItemList (dnd5e-actions.js:73)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:26)
    at ActionHandler5e.buildActionList (actionHandler.js:38)
    at TokenActionHUD.updateHud (tokenactionhud.js:258)

I understand there's a compatibility risk for the module with the latest version, unsure if this is related or if there is another bug at work here.
Thanks!

**Comment by espositos** [comment]
Nah, almost certainly I fucked something up. I'll look into it.

**Comment by espositos** [comment]
Which version of DND5e are you running? 0.93 or 0.94?

**Comment by espositos** [comment]
I can't replicate this, but if you can contact me on Discord (^ and stick#0520) we can troubleshoot it.

**Comment by astraldreadnaught** [comment]
Was totally on me! I've been running DND5E 0.88 this whole time...
HUD works just great on 0.94! Thanks so much for the quick response though! I've never gotten any notification that FVTT updated their version of 5E, never even thought to check.

**Comment by espositos** [comment]
🐱‍💻nice
