### ISSUE TITLE
Feature Request: Add “shift key” feature to invoke the standard dialogue box for rolls.

### ISSUE THREAD

**Issue by Drunemeton** [espositos/fvtt-tokenactionhud#53]
If an on-the-fly modifier needs to be added to a roll there’s no current way to do that. 

However since the “shift” key isn’t mapped I’m requesting that it be added. 

When the “shift” key is depressed TAHUD should simply display the standard roll dialog (with the entry field for modifiers and the regular buttons).

**Comment by espositos** [comment]
Which system or roll handler are you requesting it for?

**Comment by Drunemeton** [comment]
D&D 5e.

**Comment by espositos** [comment]
I'll see what I can do. It might be right-click or something that ends up offering the normal roll 'modifier' dialogue, because ctrl/shift/alt are used everywhere (almost?) for advantage/disadvantage/quick roll.

**Comment by espositos** [comment]
I have set it to alt+right click for a damage dialogue and ctrl+right click for an attack dialogue. This removes some functionality from the Minor QoL and Better Rolls, removing the ability to roll versatile damage, but I'm not sure anyone was using that feature anyway, and this seems useful.
