### ISSUE TITLE
Bug: Better Rolls Not Working as Roll Handler

### ISSUE THREAD

**Issue by Dumbhuman** [espositos/fvtt-tokenactionhud#56]
Everything had been working well previously, but today only the Skills/Checks/Utility buttons do anything.  The other buttons for Inventory/Spells/Features do nothing when clicked if I have Better Rolls set as the roll handler.  If I change the setting to using Core 5E or Minor QoL, the buttons work again (although curiously on my test subject, an Acolyte from the SRD Monsters, clicking the spell Light through Token Action HUD doesn't do anything, but the other spells work).

I verified that Better Rolls still works through the character sheet buttons.  I also verified that the problem persists when only Token Action HUD, Better Rolls, and Tidy UI Settings are enabled.

**Comment by espositos** [comment]
Yep, sorry, I noticed the messages this morning. It should be fixed now.
