### ISSUE TITLE
Allow to roll saving throws, ability and skill checks for multiple token selection.

### ISSUE THREAD

**Issue by kimitsu** [espositos/fvtt-tokenactionhud#57]
Handling skill checks and saving throws for multiple tokens is currently a slow process: select each one individually, navigate to the proper token action, click (the details here may be different depending on what kind of rolling framework you use, I use BeterRolls, which means it's one click and it rolls).
I wonder if it's possible to display Token Action HUD, limited to checks and saves, for multiple token selection, and then allow them to roll their checks simultaneously (with the same advantage/disadvantage setting for all rolls)?

**Comment by espositos** [comment]
I like the idea, but it's a bigger change. I'll have to think about how to implement it.

**Comment by espositos** [comment]
This has been added for DND5e and I'll try to roll it out slowly for other systems as well, Pathfinder 2E excluded because they handle NPC and PC skills differently and ain't no body got time for that
