### ISSUE TITLE
No NPC HUD

### ISSUE THREAD

**Issue by Khybersghost** [espositos/fvtt-tokenactionhud#58]
HUD isn't showing up for NPCs any longer.

**Comment by espositos** [comment]
Hey, I assume this is PF2E? The NPCs I've tested in 1.9.6 appear to work normally. Are you able to provide any screenshots of the errors you're getting?

**Comment by Khybersghost** [comment]
This is PF2e yes, sorry. Forgot that important detail. I didn't see any errors in the console but I will check again.

**Comment by Khybersghost** [comment]
![NPCHud](https://user-images.githubusercontent.com/65833146/89945074-a1f61f00-dbd5-11ea-8299-f2f26b06c2af.png)
