### ISSUE TITLE
Bug: Show HUD Title not displaying token's alias

### ISSUE THREAD

**Issue by ZBell** [espositos/fvtt-tokenactionhud#59]
Hello, I'm not sure this is a bug but based on my reading of the setting in question it isn't working right.  This is in 5e D&D.  I have the Show HUD Title option selected and it is displaying the Actor that the token represents, and not the Token's name.  If it's possible to have an option to display the token name instead of the Actor name that might be useful to some folks.
![Token_Action_Hud-Image](https://user-images.githubusercontent.com/4707545/90078427-e0bdcf00-dcd2-11ea-8f7e-61222f4315d2.png)

**Comment by espositos** [comment]
I'll check it. Yeah, it should show the token name.
