### ISSUE TITLE
Built in Pathfinder 2e support?

### ISSUE THREAD

**Issue by SomethingSimpl** [espositos/fvtt-tokenactionhud#6]
Hi, Id love to see a built in Pathfinder 2e support! The categories could be essentially the same as they are set in DnD 5e honestly.

**Comment by espositos** [comment]
Hey, I will appeal to the Pathfinder 2E community and see if there is someone who knows the system and can code who will help me.

**Comment by espositos** [comment]
I've implemented PF2E support. It's not as fully-featured as the DND5e support, partly because the PF2E system isn't quite as fully-featured. I'll try to keep development going as PF2E improves.
