### ISSUE TITLE
Option to render full names of skills

### ISSUE THREAD

**Issue by Puddinglord** [espositos/fvtt-tokenactionhud#62]
My group and I play Pathfinder 2e and the list of skills being abbreviated is confusing to go through unless you know it really well. Could there be an option to expand everything to its full name?

**Comment by espositos** [comment]
I've contacted you on Discord, but I'm pretty sure this is already implemented (see attachment). But let me know on Discord if you meant something else.
![image](https://user-images.githubusercontent.com/14127543/90342415-82615b00-e008-11ea-9d98-0fd0842ba657.png)
