### ISSUE TITLE
Unclear how to add features to a custom category on the HUD?

### ISSUE THREAD

**Issue by TatianaKat** [espositos/fvtt-tokenactionhud#63]
Hi there,

Forgive me if this was very obvious, but one of my players has asked how to add features to a custom category in the HUD. How can one do this? Thank you!

**Comment by TatianaKat** [comment]
As an update to this, I did discover how to add them by making macros. The trouble now seems to be getting it to work with BetterRolls. When I make a macro for the character to use the feature in question, it works fine when fired from the hotbar, but when added to a compendium and put onto the Token Action HUD through a custom category, I get a 'macro syntax error' popping up.

Is there a way to make a BetterRolls macro work with this feature?

**Comment by espositos** [comment]
I'm not totally sure, I'd have to look at the macro in question. Would you be able to post the macro here and I can test it? Or contact me on Discord if you don't want to post it publiclly.

**Comment by espositos** [comment]
Regarding adding new categories, yeah, i am bad at documenting things. I guess you have figured it out but you basically

1. hover ove r

hover over the HU

**Comment by TatianaKat** [comment]
The macro in question was a really simple one, just..

`BetterRolls.quickRollByName("Cherry", "Throw Bomb");`

When I use it from the hotbar it's working just fine, but it gets an error when fired from the HUD.

**Comment by espositos** [comment]
👍 I'll investigate

**Comment by espositos** [comment]
I'm sorry, I can't replicate this. Is there any chance I could join your server and test it out there?

**Comment by TatianaKat** [comment]
My server has some.. uh, sensitive material given the nature of the campaign that I'm not 100% sure my players would be comfortable with a stranger seeing ^^; With that said, here's a screenshot of the way the macro is set up and the relevant related materials.

https://i.gyazo.com/34cc57fe08d8f985ae4a75562009afac.jpg

The best I can do is maybe throw you the error from the console?

`TypeError: Cannot read property 'ctrlKey' of undefined
    at KeyboardManager.isCtrl (foundry.js:2312)
    at CustomItemRoll.checkEvent (custom-roll.js:435)
    at new CustomItemRoll (custom-roll.js:403)
    at Object.quickRollByName (betterrolls5e.js:723)
    at Macro.eval (eval at callScriptMacroFunction (Macros.js:176), <anonymous>:5:29)
    at Macro.callScriptMacroFunction [as callScriptFunction] (Macros.js:179)
    at Macro.renderMacro [as renderContent] (Macros.js:197)
    at Macro.executeMacro (Macros.js:221)
    at compendiumMacroPreHandler.js:53`

**Comment by espositos** [comment]
I am not totally certain, but my suspicion is that another module is interfering with the 'click' event, probably because it goes through a compendium. If it's possible, I would be interested in knowing if the macro works when BetterRolls and the Token Action HUD are the only modules running.

Otherwise, if it is already a macro in the Macro Directory (the directory that usually feeds the hotbar), you can also set up macro subcategories by entering free-text when prompted by the subcategory filter (this description sucks, see the gif attached). This might not be as convenient, but it's worth trying out.
![macroexample](https://user-images.githubusercontent.com/14127543/90442253-aa20f380-e0da-11ea-924d-abefbf96c53a.gif)


After that, I am not really sure. From the sounds of the error text, it doesn't look like something happening internally to the Token Action HUD, which makes the issue a bit hard to pin down.

Sorry, I'm off to sleep now, but I'll check back tomorrow.

**Comment by TatianaKat** [comment]
This solution actually worked, oddly enough! As for what the problem might be, could it have something to do with BetterRolls and Minor-QOL together? That's caused a few issues for me in the past.

**Comment by espositos** [comment]
I don't think so. I would suspect anything that interacts with compendiums, like a compendium browser. They're the only other thing between the HUD and betterrolls in that process.

**Comment by TatianaKat** [comment]
I don't think I've got anything like that installed unless perhaps it's Plutonium?

**Comment by espositos** [comment]
I'll test it out with plutonium tomorrow, but I'm glad the workaround works anyway

**Comment by espositos** [comment]
Plutonium doesn't seem to have anything to do with the issue as far as I can tell, so I'm not sure what's going on. Just to check, are you happy with the workaround? If so, I'll stop investigating this until I can find more information.

**Comment by TatianaKat** [comment]
I think the workaround is fine if a little clumsy!

The best I can do at this point as far as info goes is give you this list of the modules I'm using, maybe you can spot the problem here amongst them.

`Cautious Gamemaster's Pack
Dancing Lights
Show Drag Distance
Better NPC Sheet 5e
Better Rolls for 5e
Combat Utility Belt
Combat Ready!
Darker Vision for 5e
Deselection
Dice So Nice!
Dynamic Effects
Easy Target
The Furnace
FXMaster
Health Estimates
Layer Hotkeys
Let Me Roll That For You
Minor Quality of Life Improvements
MusicAssist
Plutonium
Polyglot
Skill Customization for D&D5e
Token Action HUD
GM Token-Drag Visibility
Token Mold
Token Tooltip
Torch
Turn Marker
Tweak Playlist`

**Comment by espositos** [comment]
Yeah, none of them look like they would be the issue, as far as I can tell. Searching on the Foundry discord for ctrlkey and undefined brings up a couple of other reports that also seem to be related to BetterRolls and a similar error, but it doesn't sound like it's very common. I will continue keeping an eye out for the error, but as I said, I don't think the error is arising from the HUD itself.

**Comment by TatianaKat** [comment]
Okay! Thank you for all your help anyway!

**Comment by espositos** [comment]
Closing this for now but I will keep an eye out. I meant to ask as well, in case you ever check this in the future, if you were using a non-standard keyboard layout?
