### ISSUE TITLE
PF2E Monster Strikes Not Displayed

### ISSUE THREAD

**Issue by laurieathey** [espositos/fvtt-tokenactionhud#64]
Hey,
1. Love the mod.
2. My players LOVE the mod. They barely use the sheets anymore 👍 
3. I basically have to ignore this mod as GM cause it doesn't do what I need most: Attacks.

I'm not sure why because other actions are in there, but all the attacks are omitted as well as some abilities from the other sections. 
EG: 
![image](https://user-images.githubusercontent.com/11553364/90512676-ca929180-e15e-11ea-8f93-132f1c495681.png)

If you could figure out why they're not showing up you'd be saving me a lot of time as well as my players :)

**Comment by espositos** [comment]
They definitely should be there. Are there any errors in the console?
![image](https://user-images.githubusercontent.com/14127543/90550422-3b9e6d00-e190-11ea-93dd-243f0a0a1fcb.png)

**Comment by laurieathey** [comment]
Hey, 

So I'm running this on V0.6.5 of Foundry (Via Forge, set to always use latest stable)
I was on 1.9.something of PF2e, just updated it to see what if that would fix it.
I forgot to check what version of your mode I was on but I installed it last week some time if that helps.

And updating your mod fixed it. Whatever was wrong was to do with me being out of date so I take it all back, you're awesome, your mode is awesome, have a great night 👍 

<3
