### ISSUE TITLE
midi-qol support

### ISSUE THREAD

**Issue by tposney** [espositos/fvtt-tokenactionhud#65]
I've released midi-qol a replacement for minor-qol and the rolls have changed.

To roll an item you just call item.roll as in for standard DND. For key support you can call item.roll({event}), where event has shiftKey, altKey, crtflKey to fast forward rolls.

If you wanted to support midi-qol I'd be grateful.

**Comment by espositos** [comment]
I'll wait for feedback from Discord, but otherwise I think it's done. But yes, of course, I'll try to include support for Midi QoL.

**Comment by espositos** [comment]
I think it's fixed for the moment but I'll watch out for anything further.
