### ISSUE TITLE
unable to move hud

### ISSUE THREAD

**Issue by Jmilesy** [espositos/fvtt-tokenactionhud#68]
I have a problem when the hud has moved to next to the actor token.  

I cannot seem to move the hud as I used to and it is covering the status effects.

![unknown](https://user-images.githubusercontent.com/34949583/91266435-2bc2f200-e769-11ea-9da6-cdc53e961564.png)

**Comment by espositos** [comment]
Hey. I replied to you in Discord as well. I had removed the ability to reposition when the HUD is hovering status, but I've readded it in the latest patch. Let me know if you continue to have any issues.
