### ISSUE TITLE
Save DC's not appearing with Better Rolls

### ISSUE THREAD

**Issue by RulyTafzil** [espositos/fvtt-tokenactionhud#7]
When using Better Rolls configured to show a save dc with an attack, the save DC does not appear on the roll. Triggering the roll normally via the character sheet shows the save DC. Using the hud link does not.

**Comment by espositos** [comment]
Hopefully resolved, but right-clicking on a versatile weapon will roll the versatile attack, and I currently don't know how to roll the versatile attack and show the quick roll-selected fields.
