### ISSUE TITLE
[Pathfinder 2e] No remove button for - Spontaneous & Innate spells

### ISSUE THREAD

**Issue by zLaddeus** [espositos/fvtt-tokenactionhud#71]
The little "-" icon doesn't appear on Innate spells.

It would be useful to be able to mark off spells used. PF2e doesn't always let Innate spells be cast how many times they want.
Having the remove "-" button would help to track "uses per day" and even for Spontaneous casters, which are bound to have spells at different levels.

**Comment by espositos** [comment]
The HUD doesn't hold any information about the spells, it just reads from their details, so if you would like innate spells or spontaneous spells to have use tracking I would petition the PF2E devs instead and then I can use the information they add to the spell object. If uses per day is already tracked in these spells and I'm mistaken, could you take a screenshot of where you find it in the details and I'll look into it.

**Comment by espositos** [comment]
I am closing this for the moment, but if or when PF2E adds use data to the spells I will be happy to take another look at it.
