### ISSUE TITLE
[Pathfinder 2e] Templates doesn't work for some spells & types of areas.

### ISSUE THREAD

**Issue by zLaddeus** [espositos/fvtt-tokenactionhud#72]
Hi! I want to start with saying; I don't know much about programming or module-making. Or even how the code in Foundry VTT work. Maybe these issues are not something that can be done in the scope of a module but I thought I'd might put them out there anyway.

Cheers!

- Looks like only spells with the 'Spell Type: Saving Throw' works with a template. Would it be possible to add it to 'Spell Attack', 'Healing', 'Utility', 'Focus' & 'Ritual' types also?

- Some spells that are exactly the same as spells that does work - doesn't. Example: 'Lightning Bolt' works but 'Hydraulic Torrent' doesn't. Both are 'Saving Throw' spells, both have "X-foot line" in their 'Area' field. But 'Hydraulic Torrent' shows up as "Place a 60ft ERROR" (while 'Lightning Bolt' shows "Place a 120ft ray") in the Chat. If pressed and trying to put the template out (which shows just the icon, not the outline) displays an error message _"MeasuredTemplate field t failed provided validation rule"_. Even if 'Hydraulic Torrent' is changed to exact stats of the 'Lightning Bolt' it doesn't work. However changing 'Hydraulic Torrent' to "10-foot Burst" makes it display a 10 foot circle template.

- The spell 'Weapon Storm' have an area of "30-foot cone or 10-foot emanation", which creates a "Place a 30ft,10ft ERROR" button in the chat, and displaces the _"MeasuredTemplate field t failed provided validation rule"_ error. Would it be possible to get 2 buttons, one for each?

- Spells that uses 'Emanation' type of area doesn't work. 'Emanation' is a rectangle area around a square. 'Burst' works for this, but 'Emanation' isn't connected to the 'Circle' template, as 'Burst' is. Would it be possible to connect this?

- Few spells have an Area of "1 5-foot square", 'Flaming Sphere' for example. 'Square' doesn't work, and could perhaps use the 'Rectangle' template since you can't do a '1 5-foot square' with the circle tool?

- A number of templates doesn't work because they are spelt with a lower-case letter, like Cone vs. cone. Would it be possible to not make the module case sensitive?

**Comment by espositos** [comment]
Hey zLaddeus, I will look into this with the PF2E channel, but as far as I know there is no automatic template placing in PF2E, so these issues are probably not the domain of the Token Action HUD but the interaction of some other module. However, I will investigate.

**Comment by espositos** [comment]
Hi zLaddeus, as far as I can tell, these are issues with the PF2E Quick Rolls module, which is responsible for interpreting the spell chat card and creating the 'Place template' button, along with the 'error' messages and things like that.
