### ISSUE TITLE
[Starfinder] Unable to see additional profession skills

### ISSUE THREAD

**Issue by supernovajm** [espositos/fvtt-tokenactionhud#73]
If an actor has more than one profession skill, it isn't displayed in the action hud. Possibly related, naming the original profession skill doesn't change the name to Profession(name)

![image](https://user-images.githubusercontent.com/24704061/93891116-0e763a80-fcb9-11ea-8466-ca34ed782a85.png)

![image](https://user-images.githubusercontent.com/24704061/93891098-09b18680-fcb9-11ea-9b69-802b60e56ccb.png)

**Comment by espositos** [comment]
Should be in the latest patch if you want to test it. Let me know if you have any issues.

**Comment by supernovajm** [comment]
Confirmed working with latest patch!
