### ISSUE TITLE
[Pathfinder 2E] Exploration and Downtime actions not visible

### ISSUE THREAD

**Issue by JerkyGunner** [espositos/fvtt-tokenactionhud#74]
When hovering over the Actions tab, it only shows the possible Encounter actions. Those in the Exploration or Downtime tab aren't visible and I can't seem to find a way to make them so.

**Comment by espositos** [comment]
Encounter and Downtime activities are classified as passive, which the HUD ignores at this stage. I'll try to add a setting to show them in the next patch.

**Comment by espositos** [comment]
In the meantime, you can get them to display by assigning them an action other than 'passive'

**Comment by espositos** [comment]
In the 0.7.16 patch
