### ISSUE TITLE
Pathfinder 1 support

### ISSUE THREAD

**Issue by emdant** [espositos/fvtt-tokenactionhud#75]
I really like this module, but my friends and I are playing pf1e at the moment, will this system ever be supported?

**Comment by espositos** [comment]
I had no plans to, but I will ask in the PF1 channel when I get some time to see how easy it would be to support.

**Comment by Nargath** [comment]
I wouldn't say no to this being developed for PF1!

**Comment by espositos** [comment]
Sorry, no time this weekend so I'll try to look into it during the week.

**Comment by Ironxxx** [comment]
Would add to Nargath's comment, love this mod in Starfinder, would really appreciate it for PF1 too.

**Comment by espositos** [comment]
Just to say I am working on this slowly but have started some new work and have less time for it than previously, so it will be a bit slow.

**Comment by espositos** [comment]
It's in. I'll close this and people can open separate issues for the slew of bugs that I'm sure now exist in it.
