### ISSUE TITLE
[Issue] doesn't work with Better Rolls 5e (throws error)

### ISSUE THREAD

**Issue by PalaNolho** [espositos/fvtt-tokenactionhud#78]
The module is not working when we select to use the Better Rolls 5e module to resolve the rolls.
It's throwing an error in the console and nothing happens.

i'm using:
- **Foundry** v0.6.6
- **D&D5e** v0.98
- **Better Rolls 5e** v0.1.9
- **Token Action Hub** v0.7.17

![2020-10-10_00-33-27](https://user-images.githubusercontent.com/6009914/95639476-7639cd00-0a90-11eb-9e25-d215f2f394db.png)

**Comment by espositos** [comment]
I think we've established it was due to an old BetterRolls version, but let me know if you have more issues.
