### ISSUE TITLE
Enhancement: Option to click instead of hover for interaction

### ISSUE THREAD

**Issue by Mr-Monocyte** [espositos/fvtt-tokenactionhud#81]
Not a common thing, I know, but one of my players can only play on mobile right now. Mobile support is minimal for Foundry in general but this HUD could work great if they could interact with it via touchscreen. 

Maybe the option would allow clicking to open/close each category and move the add/remove subcategory popup to an icon at the far right? Right now, clicking brings up this subcategory popup (and exapands the category) but canceling the popup also collapses the category.

**Comment by espositos** [comment]
I'll look into it, but I can't promise anything.

**Comment by Mr-Monocyte** [comment]
Understood. 
BTW, I love your module.
Thanks for your time and effort!
