### ISSUE TITLE
Error for Vehicle

### ISSUE THREAD

**Issue by rinnocenti** [espositos/fvtt-tokenactionhud#86]
![image](https://user-images.githubusercontent.com/3178127/97210865-f48ab480-179c-11eb-9720-f12c987b693f.png)

the token tries to create HUD for vehicles but does not find any items

**Comment by espositos** [comment]
I really don't know what I'm doing with vehicles. Do they roll saves? Do they have actions? Is there an explanation of them somewhere?

**Comment by rinnocenti** [comment]
https://5e.tools/vehicles.html#galley_gos

they do not check attacks, but it tests physical attributes, suffer and make attacks with their own weapons and equipment and features.

**Comment by espositos** [comment]
I have added a check for vehicles so it should no longer crash when it tries to add spells or skills to the HUD from a vehicle, but if you have an export of a vehicle complete with items, feats, or crew actions that I could use as an example, that would be really helpful.
