### ISSUE TITLE
Spells not working when cast through hud (5e on 0.7.5)

### ISSUE THREAD

**Issue by SnoringMountain** [espositos/fvtt-tokenactionhud#88]
when casting some spells through the HUD a slot is used but nothing else happens,
so far i have seen this with:
Earth Tremor,
Ice Knife,
Guiding Bolt
these all work correctly when cast from the spell sheet

**Comment by espositos** [comment]
I cannot replicate this with Guiding Bolt. Neither Earth Tremor or Ice Knife are part of the SRD so I can't really test it with them. Can you provide any error logs from your console? Or let me know any other information about the problem?

**Comment by espositos** [comment]
Hi SnoringMountain, feel free to reopen this if you can provide more information, but at the moment I cannot reproduce this at all.
