### ISSUE TITLE
PF2 Monster attacks not available on HUD

### ISSUE THREAD

**Issue by apoapostolov** [espositos/fvtt-tokenactionhud#9]
Monster attacks are different from player strikes and do not populate on HUD. Devteam might make the uniform at some point in the future but for now, monster attacks are a legacy format that needs to be specially supported.

**Comment by espositos** [comment]
Yep, good to know. It's because of a misunderstanding on my part. I'll look at fixing it in the next patch.

**Comment by apoapostolov** [comment]
As discussed on Discord: also have HUD button for monster damage effects (i.e. warg's Plus Grab)
