### ISSUE TITLE
Option to move skills and tools as subcategory of "Checks"

### ISSUE THREAD

**Issue by benbarbour** [espositos/fvtt-tokenactionhud#92]
I think the Checks header should include the rows for tools (if they have the item) and skills. For example: "make a thieves tools check" or "can I get a Stealth check from everyone?" The natural category is "checks", I think.

- Checks
  - Abilities: STR, DEX, CON, INT, WIS, CHA
  - Skills: Acrobatics, ...
  - Tools: Smithing, Thieves

**Comment by espositos** [comment]
I think this is an nice idea and I would definitely consider implementing it if I ever try a major overhaul of the HUD, but I think people who are used to how it is now would complain if I changed it and I don't want to implement to distinct and separate ways of building the checks lists. Sorry.
