### ISSUE TITLE
Option to use Right-Click for Add/Remove subcategories

### ISSUE THREAD

**Issue by pesky-wobbit** [espositos/fvtt-tokenactionhud#93]
I love your module and rely on it heavily. Unfortunately, my players frequently call up the Add/Remove subcategories button. Could you include an option to disable it or have it respond to a RIGHT click instead? Thanks!

**Comment by espositos** [comment]
I can see it could be annoying. I'll try to implement this soon.

**Comment by espositos** [comment]
Implemented in 0.8.9

**Comment by pesky-wobbit** [comment]
Thank you! This module is essential!
