### ISSUE TITLE
Settings layout is incompatible with the Module Settings Sorter module

### ISSUE THREAD

**Issue by GameMaker** [espositos/fvtt-tokenactionhud#94]
Hi!

Token Action Hud is very cool!

I noticed an incompatibility with the Module Settings Sorter module, which sorts module settings alphabetically - makes it much easier to find settings.

When I ran them both, the settings for Token Action HUD were displayed along the top of the window, flowing out of the settings dialog, like this:
![image](https://user-images.githubusercontent.com/1099635/98061664-3d77e400-1e01-11eb-873e-b74a07cb4717.png)

I'll add a bug to Module Settings Sorter as well, since I'm not sure what's going on, but figured I'd let you know.

Thanks!

**Comment by espositos** [comment]
Duplicate issue
