### ISSUE TITLE
Incompatibility with Module Settings Sorter

### ISSUE THREAD

**Issue by GameMaker** [espositos/fvtt-tokenactionhud#95]
Hi!

Token Action Hud is very cool!

I noticed an incompatibility with the Module Settings Sorter module, which sorts module settings alphabetically - makes it much easier to find settings.

When I ran them both, the settings for Token Action HUD were displayed along the top of the window, flowing out of the settings dialog, like this:
![image](https://user-images.githubusercontent.com/1099635/98061664-3d77e400-1e01-11eb-873e-b74a07cb4717.png)

I'll add a bug to Module Settings Sorter as well, since I'm not sure what's going on, but figured I'd let you know.

Thanks!

EDIT: This is on Foundry 0.7.5, btw. Thanks!

**Comment by espositos** [comment]
Thanks for reporting it, I'll try to talk with Eadorin about it. The Token Action HUD doesn't do anything interesting or special with its settings.

**Comment by Grygon** [comment]
Looks like the settings page is picking up CSS meant for the TAH buttons themselves which is what's causing the issue:
![image](https://user-images.githubusercontent.com/647846/99290361-cfb9b800-2803-11eb-9608-ef194b9f4b16.png)

**Comment by espositos** [comment]
Thanks for looking into that, Grygon. Is there anything I can do from my side to resolve this?

**Comment by Grygon** [comment]
Yeah seems to be coincidence. Nothing worth doing here, you could change the identifier but I think having MSS change makes more sense so I made a PR on that end
