### ISSUE TITLE
no usage of consumable actions

### ISSUE THREAD

**Issue by Bogus73** [espositos/fvtt-tokenactionhud#96]
Hi,
I totally love your module! Today I saw that things with consumable uses are not consumed anymore.
Example: divine sense
it stays at 1 of 1 usages

Thank you for your hard work!

edit: I think it is "Better Rolls" and not your module. You have to manually add consumption under the better rolls section of the action. 
Sorry, to have bothered you.

**Comment by espositos** [comment]
No problem, always good to report something fishy :)
