### ISSUE TITLE
Requesting Support for LANCER 

### ISSUE THREAD

**Issue by Flintwyrm** [espositos/fvtt-tokenactionhud#97]
The Lancer System would greatly benefit from support from this module. I think the work you are doing here is amazing.

**Comment by espositos** [comment]
Every additional module means extra work and I only have so much time, but I will look into it. Someone from the LANCER community is also welcome to write the necessary parts and submit a pull request. If you find someone willing I'm happy to answer questions about the module.

**Comment by Flintwyrm** [comment]
I think I can do that.

**Comment by espositos** [comment]
Available in 0.9.7. Feedback is welcome
