### ISSUE TITLE
[Pathfinder 2e] Lores and Skills issue

### ISSUE THREAD

**Issue by Cosmic-Lattee** [espositos/fvtt-tokenactionhud#98]
My players are reporting a interesting little visual bug while playing PF2e with your amazing module. Each time they add a lore skill this blank button appears in the skill section. In the case below clicking on the blank button rolls the "Xulgath Lore" skill. Small bug I know but I wanted to bring it to your attention!

![image](https://user-images.githubusercontent.com/24766235/98457460-0ed57280-214d-11eb-8c46-2138555c918b.png)

**Comment by espositos** [comment]
Should be fixed.
