### ISSUE TITLE
[WFRP4e] The Weapons list is wrong (ie all weapons instead of only equipped)

### ISSUE THREAD

**Issue by sladecraven** [espositos/fvtt-tokenactionhud#99]
In the Token HUD with WFRP4 system, the "Weapons" button list all weapons objects of the token. Instead, it must list only the 'equipped' ones. They shall be filtered using the `equipped = true` flag in the weapon/item object.

**Comment by espositos** [comment]
Should be fixed in the latest patch. This will only affect characters (not NPCs).
